class AppConstants {
  // --- EXPENSES ---
  static const List<String> expenseCategories = [
    'Habitação',
    'Alimentação',
    'Transporte',
    'Saúde',
    'Educação',
    'Despesas Pessoais',
    'Lazer',
    'Assinaturas e Serviços Digitais',
    'Serviços Financeiros',
    'Investimentos', // Can be treated as expense (outflow) or transfer, user listed it under expenses
    'Impostos e Tributos',
    'Pet',
    'Imobilizado',
    'Outras Despesas',
  ];

  static const Map<String, List<String>> expenseSubcategories = {
    'Habitação': [
      'Aluguel Residência',
      'Condomínio',
      'Água',
      'Luz (Eletricidade)',
      'Gás',
      'Telefone Fixo',
      'Internet Residencial',
      'Seguro Residencial',
      'Manutenção e Reparos',
      'Serviços Domésticos',
      'Materiais de Limpeza',
    ],
    'Alimentação': [
      'Supermercado',
      'Sacolão/Hortifrúti',
      'Feira',
      'Restaurantes/Bares',
      'Lanchonetes/Cafeterias',
      'Delivery e Aplicativos',
    ],
    'Transporte': [
      'Financiamento/Aluguel de Veículo',
      'Combustível',
      'Ônibus/Metrô/Aplicativos',
      'Manutenção do Veículo',
      'IPVA/Licenciamento',
      'Seguro Auto',
      'Estacionamento e Garagem',
      'Pedágios',
      'Multas',
    ],
    'Saúde': [
      'Plano de Saúde',
      'Consultas Médicas',
      'Exames',
      'Medicamentos',
      'Despesas com Farmácia/Drogaria',
      'Dentista/Odontologia',
      'Fisioterapia e Terapias',
      'Ótica/Lentes/Óculos',
      'Aparelhos Auditivos/Ortopédicos',
    ],
    'Educação': [
      'Escola/Mensalidades',
      'Faculdade/Pós-graduação',
      'Cursos Extracurriculares',
      'Material Escolar/Acessórios',
      'Livros e Publicações',
      'Cursos Online e Plataformas',
    ],
    'Despesas Pessoais': [
      'Vestuário e Calçados',
      'Higiene Pessoal',
      'Cosméticos e Maquiagem',
      'Salão de Beleza/Cabeleireiro',
      'Barbeiro',
      'Academia e Atividades Esportivas',
      'Presentes',
    ],
    'Lazer': [
      'Viagens',
      'Hotéis e Pousadas',
      'Cinema/Teatro/Shows',
      'Ingressos e Eventos',
      'Hobbies e Coleções',
      'Mensalidades de Clubes/Associações',
      'Jogos e Assinaturas de Games',
    ],
    'Assinaturas e Serviços Digitais': [
      'Plano de TV por Assinatura',
      'Netflix e Outras Plataformas',
      'Assinaturas de Software',
      'Armazenamento em Nuvem',
    ],
    'Serviços Financeiros': [
      'Cartão de Crédito (Anuidade)',
      'Empréstimos e Financiamentos',
      'Tarifas Bancárias',
      'Seguros Diversos',
      'Consórcios',
    ],
    'Investimentos': [
      'Aplicações em Bolsa',
      'Poupança',
      'Renda Fixa',
      'Previdência Privada',
      'Fundos de Investimento',
    ],
    'Impostos e Tributos': [
      'Imposto de Renda (IR)',
      'IPTU (Imóvel)',
      'IRCBI',
      'Outras Taxas Governamentais',
    ],
    'Pet': [
      'Ração',
      'Banho e Tosa',
      'Veterinário',
      'Remédios/Suplementos',
      'Acessórios/Brinquedos',
      'Hospedagem/Creche',
    ],
    'Imobilizado': [
      'Eletrodomésticos',
      'Computador',
      'Impressora',
      'Celular',
      'Automóvel',
      'Móveis e utensilios',
      'Máquinas',
      'Equipamento',
    ],
    'Outras Despesas': [
      'Doações/Dízimos',
      'Mesada/Pensão',
      'Manutenção de Eletrodomésticos',
      'Reserva de Emergência',
    ],
  };

  // --- INCOME ---
  static const List<String> incomeCategories = [
    'Renda Principal',
    'Renda Extra',
    'Renda de Investimentos',
    'Renda de Aluguéis e Imóveis',
    'Transferências e Presentes',
    'Auxílios e Benefícios Sociais',
    'Imobilizado',
  ];

  static const Map<String, List<String>> incomeSubcategories = {
    'Renda Principal': [
      'Salário Líquido',
      'Adiantamento Salarial',
      'Comissão por Vendas',
      'Bônus por Performance',
      'Vale-Alimentação/Refeição',
      'Participação nos Lucros (PLR)',
      'Pagamento de Serviços',
      'Freelances',
      'Pró-Labore',
    ],
    'Renda Extra': [
      'Serviço como "bico"',
      'Venda de Produtos Artesanais',
      'Renda de Aplicativos',
      'Venda de Bens Pessoais',
      'Comércio Eletrônico',
      'Aluguel de Quarto/Imóvel',
      'Aluguel de Equipamentos',
      'Reembolso de Despesas',
      'Restituição de Imposto de Renda',
    ],
    'Renda de Investimentos': [
      'Juros de Poupança',
      'Rendimento de CDB/LCI/LCA',
      'Rendimento de Tesouro Direto',
      'Dividendos de Ações',
      'Juros sobre Capital Próprio',
      'Rendimento de FIIs',
      'Ganhos em ETFs',
      'Resgate de Previdência Privada',
      'Rendimento de Criptomoedas',
      'Juros de Contas Digitais',
    ],
    'Renda de Aluguéis e Imóveis': [
      'Aluguel Residencial',
      'Aluguel Comercial',
      'Arrendamento de Terras',
      'Venda de Imóveis',
    ],
    'Transferências e Presentes': [
      'Presentes em Dinheiro',
      'Herança/Legado',
      'Doações',
      'Mesada/Pensão',
      'Transferências Familiares',
    ],
    'Auxílios e Benefícios Sociais': [
      'Aposentadoria (INSS)',
      'Pensão por Morte',
      'Auxílio Emergencial',
      'Bolsa Família/Outros',
      'Seguro-Desemprego',
      'Indenização Judicial',
      'Seguro (Sinistro)',
    ],
    'Imobilizado': [
      'Eletrodomésticos',
      'Computador',
      'Impressora',
      'Celular',
      'Automóvel',
      'Móveis e utensilios',
      'Máquinas',
      'Equipamento',
    ],
  };

  static const Map<String, String> categoryDescriptions = {
    // Expenses
    'Habitação': 'Moradia, contas e manutenção',
    'Alimentação': 'Compras e refeições',
    'Transporte': 'Veículo e deslocamento',
    'Saúde': 'Cuidados médicos e medicamentos',
    'Educação': 'Ensino e aprendizado',
    'Despesas Pessoais': 'Cuidados pessoais e vestuário',
    'Lazer': 'Entretenimento e viagens',
    'Assinaturas e Serviços Digitais': 'Streaming e softwares',
    'Serviços Financeiros': 'Taxas e serviços bancários',
    'Investimentos': 'Aplicações financeiras',
    'Impostos e Tributos': 'Taxas governamentais',
    'Pet': 'Cuidados com animais de estimação',
    'Outras Despesas': 'Diversos e doações',
    // Income
    'Renda Principal': 'Salário, comissões e benefícios',
    'Renda Extra': 'Trabalhos extras e vendas',
    'Renda de Investimentos': 'Rendimentos passivos',
    'Renda de Aluguéis e Imóveis': 'Aluguéis e venda de imóveis',
    'Transferências e Presentes': 'Doações e presentes',
    'Auxílios e Benefícios Sociais': 'Aposentadoria e auxílios',
  };
}
