class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'pt_BR': {
      // Home
      'app_title': 'FinAgeVoz',
      'subtitle': 'Seu assistente financeiro',
      'status_idle': "Toque para falar ou diga 'Finanças'",
      'status_listening': "Ouvindo...",
      'status_processing': "Processando...",
      'hint_ok': "Diga \"OK\" para enviar",
      'hint_speak': "Fale o que quer e no final diga OK",
      'nav_finance': "Finanças",
      'nav_agenda': "Agenda",
      'nav_reports': "Relatórios",
      'nav_categories': "Categorias/Sub",
      
      // Status messages
      'status_tap_to_speak': "Toque para falar",
      'status_listening': "Ouvindo...",
      'status_processing': "Processando...",
      
      // Menu
      'menu_settings': "Configuração",
      'menu_help': "Ajuda",
      'menu_privacy': "Política de Privacidade",
      'menu_about': "Sobre",
      'menu_manage_data': "Gerenciar Dados",
      'menu_import_transactions': "Importar Transações (CSV)",
      'menu_import_calendar': "Importar Agenda (Google/Device)",
      'menu_export_transactions': "Exportar Transações (CSV)",
      'menu_export_calendar': "Exportar Agenda (Google/Device)",
      'select_calendar': "Selecione o Calendário",
      'select_calendar_dest': "Selecione o Calendário de Destino",
      'no_name': "Sem nome",
      'error_fetch_calendars': "Erro ao buscar calendários: ",
      'events_imported_success': " eventos importados com sucesso!",
      'no_new_events': "Nenhum evento novo encontrado.",
      'error_import_events': "Erro ao importar eventos: ",
      'error_export': "Erro ao exportar: ",
      'no_calendars_found': "Nenhum calendário encontrado ou permissão negada.",
      'transactions_imported_success': " transações importadas com sucesso!",
      'no_transactions_imported': "Nenhuma transação importada.",
      'error_import': "Erro ao importar: ",
      'transactions_count_label': "transações",
      'active_filters': "Filtros ativos: ",
      'filter_attachments': "Com Anexos",
      'filters_cleared': "Filtros limpos",
      'clear_filters': "Limpar Filtros",
      'share_report': "Compartilhar Relatório",
      'transactions_report_title': "Relatório de Transações",
      'financial_report_title': "Relatório Financeiro",
      'events_report_title': "Relatório de Eventos",
      'apply_filters': "Aplicar Filtros",
      'period_custom': "Personalizado",
      'start_date': "Data Início",
      'end_date': "Data Fim",
      'select': "Selecionar",
      'categories_subcategories': "Categorias e Subcategorias",
      'categories_label': "Categorias:",
      'subcategories_label': "Subcategorias:",
      'value_range': "Faixa de Valores",
      'min_value': "Valor Mínimo",
      'max_value': "Valor Máximo",
      'transaction_type': "Tipo de Transação",
      'installments': "Parceladas",
      'single_payments': "À Vista",
      'exclude_reversals': "Excluir Estornos",
      'period_quarter': "Trimestre",
      'new_subcategory_title': "Nova Subcategoria em ",
      'export_csv': "Exportar CSV",
      'categories_exported_success': "Categorias exportadas com sucesso!",
      'google_drive': "Google Drive",
      'total_events': "Total de Eventos:",
      'active_events': "Ativos:",
      'cancelled_events': "Cancelados:",
      'active_events_title': "Eventos Ativos",
      'cancelled_events_title': "Eventos Cancelados",
      'table_time': "Hora",
      'table_location': "Local",
      'table_title': "Título",
      'calendar_error_not_found': "Nenhum calendário encontrado ou permissão negada.",
      'calendar_fetch_error': "Erro ao buscar calendários: ",
      'event_export_error': "Erro ao exportar eventos: ",
      'voice_commands_disabled_msg': "Os comandos de voz estão desabilitados nas configurações.",
      'you_can_label': "Você pode:",
      'voice_commands_note': "Nota: Comandos de voz requerem uma chave API Groq configurada.",
      'understood': "Entendi",
      'go_to_settings': "Ir para Configurações",
      'voice_commands_setup_msg': "Para usar comandos de voz, você precisa configurar uma chave API Groq.",
      'options_label': "Opções:",
      'get_key_at': "Obtenha sua chave em: console.groq.com",
      'later': "Depois",
      'configure': "Configurar",
      'whatsapp_error': "Não foi possível abrir o WhatsApp.",
      'attachments_label': "Anexos",
      'delete_installment_msg': "Esta é uma transação parcelada. O que deseja fazer?",
      'delete_this': "Excluir esta",
      'delete_all': "Excluir todas",
      'cancelled_status': "Cancelado",
      'events_exported_success_suffix': " eventos exportados com sucesso!",
      'no_events_to_export': "Nenhum evento para exportar.",
      'mic_disabled': "Microfone desabilitado",
      'voice_commands_disabled_title': "ℹ️ Comandos de voz desabilitados",
      'manual_usage_option': "✓ Usar o app manualmente (botões e formulários)",
      'enable_voice_option': "✓ Habilitar comandos de voz em:",
      'enable_voice_path': "  Menu → Configurações → Habilitar comandos de voz",
      'api_key_not_configured': "Chave API não configurada",
      'api_key_warning_title': "⚠️ Chave API não configurada",
      'configure_api_option': "1. Configure uma chave API gratuita",
      'disable_voice_option': "2. Desabilite comandos de voz e use o app manualmente",
      'period_label': "Período: ",
      'total_transactions': "Total Transações: ",
      'total_income': "Receitas: ",
      'total_expense': "Despesas: ",
      'balance_label': "Saldo: ",
      'table_date': "Data",
      'table_description': "Descrição",
      'table_category': "Categoria",
      'table_value': "Valor",
      'category_breakdown': "Detalhamento por Categoria",
      
      // Messages
      'msg_enable_voice': "Habilite comandos de voz nas Configurações para usar o microfone",
      'msg_configure_api': "Configure uma chave API nas Configurações para usar comandos de voz",
      'about_title': "Sobre o FinAgeVoz",
      'about_version': "Versão 1.0.0",
      'about_description': "Seu assistente financeiro e de agenda inteligente.",
      'about_developed_by': "Desenvolvido por:",
      'about_company': "Multiverso Digital",
      'about_email_label': "E-mail:",
      'about_email': "contato@multiversodigita.com.br",
      
      // Help Dialog
      'help_title': "Comandos de Voz",
      'help_transactions': "💰 Transações:",
      'help_trans_1': "• \"Gastei 50 reais na padaria\"",
      'help_trans_2': "• \"Recebi 1000 reais de salário\"",
      'help_trans_3': "• \"Comprei TV de 2000 reais em 10x\"",
      'help_agenda': "📅 Agenda:",
      'help_agenda_1': "• \"Reunião amanhã às 14h\"",
      'help_agenda_2': "• \"Pagar luz dia 15\"",
      'help_attachments': "📎 Anexos e Compartilhamento:",
      'help_attach_1': "• Adicione fotos e PDFs a transações e eventos.",
      'help_attach_2': "• Compartilhe relatórios via WhatsApp.",
      'help_settings': "⚙️ Configurações:",
      'help_settings_1': "• Controle se o app fala os eventos ao abrir.",
      'help_settings_2': "• Gerencie categorias e idioma.",
      'help_navigation': "📱 Navegação:",
      'help_nav_1': "• \"Abrir finanças\"",
      'help_nav_2': "• \"Abrir agenda\"",
      'help_nav_3': "• \"Ver relatórios\"",
      'help_tips': "💡 Dicas:",
      'help_tip_1': "• Fale naturalmente.",
      'help_tip_2': "• Aguarde o microfone pulsar.",
      'help_important': "⚠️ Importante:",
      'help_imp_1': "• O reconhecimento de voz requer internet.",
      'help_imp_2': "• Se o limite de dados da operadora for atingido, os comandos podem parar de funcionar.",
      'help_api_limit': "🔑 Limite de API:",
      'help_api_1': "• O app usa inteligência artificial com limite diário gratuito.",
      'help_api_2': "• Se atingir o limite, aguarde algumas horas ou configure uma nova chave API.",
      'help_api_3': "• Acesse Menu → Configurações → Groq API Key para adicionar sua própria chave.",
      'help_api_4': "• Obtenha uma chave gratuita em: console.groq.com",
      'help_recommendation': "💎 Recomendação para Uso Intenso:",
      'help_rec_1': "• Para até 100 transações/dia, recomendamos o plano pago Groq.",
      'help_rec_2': "• Modelo: Llama 3.3 70B Versatile",
      'help_rec_3': "• Custo: ~USD 10.35/mês (pay-as-you-go)",
      'help_rec_4': "• Sem limite diário, alta precisão e velocidade.",
      'menu_exit': "Sair",
      
      // Finance
      'finance_title': "Finanças",
      'balance_total': "Saldo Total",
      'income': "Receitas",
      'expenses': "Despesas",
      'filter_all': "Todos",
      'filter_income': "Receitas",
      'filter_expense': "Despesas",
      'add_transaction': "Adicionar Transação",
      'is_installment': "Parcelado?",
      'down_payment': "Valor da Entrada",
      'installment_count': "Nº de Parcelas",
      'installment_amount': "Valor da Parcela",
      'total_calculated': "Total Calculado: ",

      'empty_transactions': "Nenhuma transação encontrada.",
      'select_date': "Selecionar Data",
      'period_today': "Hoje",
      'period_week': "Esta Semana",
      'search_hint': "Buscar transações...",
      
      // Agenda
      'agenda_title': "Agenda",
      'empty_events': "Nenhum evento para este dia.",
      'search_hint_events': "Buscar eventos...",
      
      // Reports
      'reports_title': "Relatórios",
      'period_month': "Este Mês",
      'period_quarter': "Este Trimestre",
      'period_year': "Este Ano",
      'chart_income_expense': "Receitas vs Despesas",
      'chart_expenses_category': "Despesas por Categoria",
      'detailed_transactions': "Transações Detalhadas",
      'export_pdf': "Exportar PDF",
      'installments_report_title': "Relatório de Parcelas",
      'share_whatsapp': "Compartilhar no WhatsApp",
      'error_share_pdf': "Erro ao compartilhar PDF: ",
      'no_installments_found': "Nenhum parcelamento encontrado",
      'year_filter': "Ano: ",
      'month_filter': "Mês: ",
      'no_filtered_installments': "Nenhuma parcela encontrada com os filtros selecionados",
      'total_label': "Total: ",
      'advanced_filters': "Filtros Avançados",
      'view_installments': "Ver Parcelamentos",
      'share': "Compartilhar",
      'clear': "Limpar",
      'period_quarter_short': "Trimestre",
      'period_year_short': "Ano",
      'period_last_7': "Últimos 7 dias",
      'period_last_30': "Últimos 30 dias",
      'period_last_90': "Últimos 90 dias",
      'categories_count': "categoria(s)",
      'subcategories_count': "subcategoria(s)",
      'filtered_values': "Valores filtrados",
      'no_expenses': "sem despesas",
      'no_income': "sem receitas",
      'no_installments': "sem parceladas",
      'no_single_payments': "sem à vista",
      
      // Categories
      'categories_title': "Categorias",
      'tab_expense': "Despesas",
      'tab_income': "Receitas",
      'add_category': "Nova Categoria",
      'edit_category': "Editar Categoria",
      'delete_category': "Excluir Categoria",
      'confirm_delete': "Tem certeza que deseja excluir?",
      'cancel': "Cancelar",
      'save': "Salvar",
      'delete': "Excluir",
      'name': "Nome",
      'amount': "Valor",
      'date': "Data",
      'category': "Categoria",
      'subcategory': "Subcategoria",
      'type': "Tipo",
      'description': "Descrição",
      'close': "Fechar",
      'delete_transaction': "Excluir Transação",
      'delete_event': "Excluir Evento",
      'expense': "Despesa",
      'no_transactions': "Nenhuma transação encontrada",
      'no_events': "Nenhum evento encontrado",
      'transfer': "Transferir",
      'cancel_event': "Cancelar",
      'reactivate': "Reativar",
      'reverse': "Estornar",
      'edit': "Editar",
      'confirm_reverse': "Confirmar estorno de",
      'reversal_of': "Estorno de",
      'is_expense': "É despesa?",
      'invalid_data': "Dados inválidos",
      'pdf_generated': "PDF gerado com sucesso!",
      'error': "Erro",
      'data_management': "Gerenciar Dados",
      'database_statistics': "Estatísticas do Banco",
      'transactions': "transações",
      'events': "eventos",
      'categories': "categorias",
      'sign_in': "Entrar",
      'sign_out': "Sair",
      'signed_in_as': "Conectado como",
      'backup_and_clean': "Backup e Limpeza",
      'clean_data_older_than': "Limpar dados anteriores a",
      '6_months': "6 meses",
      '1_year': "1 ano",
      '2_years': "2 anos",
      'backup_and_clean_button': "Fazer Backup e Limpar",
      'available_backups': "Backups Disponíveis",
      'no_backups': "Nenhum backup encontrado",
      'restore': "Restaurar",
      'confirm_backup_clean': "Confirmar Backup e Limpeza",
      'confirm_backup_clean_message': "Os dados antigos serão salvos no Google Drive e depois removidos do dispositivo. Deseja continuar?",
      'continue': "Continuar",
      'google_signin_failed': "Falha ao fazer login no Google",
      'backup_success': "Backup realizado com sucesso",
      'confirm_restore': "Confirmar Restauração",
      'confirm_restore_message': "Os dados do backup serão importados. Deseja continuar?",
      'restore_success': "Dados restaurados com sucesso",
      'database_size': "Tamanho do Banco",
      'of_max_size': "do tamanho máximo",
      'quick_access': "ACESSO RÁPIDO",

      'no_categories': "Nenhuma categoria encontrada",
      'no_subcategories': "Nenhuma subcategoria",
      'status': "Status",
      'cancelled': "Cancelado",
      'danger_zone': "Zona de Perigo",
      'wipe_all_data': "Apagar TODOS os Dados",
      
      // Settings / Onboarding
      'settings_title': "Configurações",
      'onboarding_title': "Configuração Inicial",
      'wake_word_label': "Senha de Voz",
      'wake_word_hint': "Ex: Jarvis",
      'language_label': "Idioma / Language",
      'groq_label': "Groq AI (Opcional)",
      'groq_desc': "Para uma resposta muito mais rápida, use a Groq.",
      'groq_hint': "gsk_...",
      'save_continue': "Salvar e Continuar",
      'save_btn': "Salvar",
      'error_password': "Por favor, defina uma senha de voz.",
      'saved_settings': "Configurações salvas!",
      'classify_transaction': "Classificar Transação",
      'policy_title': "Política de Privacidade",
      'about_title': "Sobre",
      'version_label': "Versão",
      'developed_by': "Desenvolvido por:",
      'contact_label': "Contato:",
      'help_usage_title': "Como usar o FinAgeVoz",
      'important_label': "Importante:",
      'command_examples_label': "Exemplos de Comandos:",
      'understood_btn': "Entendi",
      'help_tooltip': "Ajuda",
      'categories_tooltip': "Categorias",
      'error_pdf_gen': "Erro ao gerar PDF",
      'get_groq_key_title': "Obter Chave Groq",
      'no_key_link': "Não tem uma chave? Clique aqui",
      'how_to_get_key_tooltip': "Como obter a chave?",
      'mic_init_error': "Erro ao iniciar microfone. Tente novamente.",
      'category_name_label': "Nome",
      'category_desc_label': "Descrição",
      'subcategory_name_label': "Nome da Subcategoria",
      'add_subcategory_tooltip': "Adicionar Subcategoria",
      'delete_category_error': "Não é possível excluir categoria com transações associadas.",
      'groq_api_key_label': "Chave da API Groq",
      'settings_general': "Geral",
      'settings_announce_events': "Sempre anunciar eventos",
      'settings_announce_events_desc': "Falar eventos ao abrir o app mesmo se já ditos",
      'settings_enable_voice': "Habilitar comandos de voz",
      'settings_enable_voice_desc': "Usar IA para processar comandos de voz",
      'voice_enabled_msg': "Comandos de voz habilitados. Reinicie o app para aplicar.",
      'voice_disabled_msg': "Comandos de voz desabilitados. Use o app manualmente.",
      'settings_data': "Dados",
      'settings_reset_categories': "Resetar Categorias",
      'settings_reset_categories_desc': "Restaura as categorias padrão",
      'settings_reset_app': "Resetar App (Apagar Tudo)",
      'settings_reset_app_desc': "Apaga todas as transações e eventos",
      'settings_api_title': "API para Comandos de Voz",
      'settings_api_in_use': "API em uso:",
      'settings_no_api': "Nenhuma API configurada",
      'settings_configured': "Configurada",
      'settings_not_configured': "Não configurada",
      'how_to_get_key_title': "Como obter sua chave Groq API:",
      'get_key_step_1': "1. Acesse: console.groq.com",
      'get_key_step_2': "2. Faça login ou crie uma conta gratuita",
      'get_key_step_3': "3. Vá em \"API Keys\" no menu lateral",
      'get_key_step_4': "4. Clique em \"Create API Key\"",
      'get_key_step_5': "5. Copie a chave gerada (começa com \"gsk_\")",
      'paste_key_below': "Cole sua chave abaixo:",
      'api_key_label': "Chave API",
      'api_key_helper': "Obrigatório para usar o app",
      'api_key_updated': "Chave API atualizada!",
      'confirm_reset_categories_title': "Resetar Categorias?",
      'confirm_reset_categories_msg': "Isso irá restaurar as categorias originais. Categorias personalizadas não serão afetadas, mas nomes padrão serão resetados para o idioma atual.",
      'reset': "Resetar",
      'categories_reset_success': "Categorias resetadas com sucesso!",
      'confirm_wipe_title': "Apagar TUDO?",
      'confirm_wipe_msg': "Tem certeza que deseja apagar TODAS as transações e eventos? Esta ação não pode ser desfeita.",
      'wipe_all': "Apagar TUDO",
      'data_wiped_msg': "Dados apagados: {transactions} transações, {events} eventos.",
      'error_prefix': "Erro: ",
      'language_changed_msg': "Idioma alterado. Reinicie o app para aplicar em todas as telas.",
      
      // Categories & Subcategories
      'cat_housing': "Habitação",
      'cat_food': "Alimentação",
      'cat_transport': "Transporte",
      'cat_health': "Saúde",
      'cat_education': "Educação",
      'cat_personal': "Despesas Pessoais",
      'cat_leisure': "Lazer",
      'cat_subscriptions': "Assinaturas e Serviços Digitais",
      'cat_financial': "Serviços Financeiros",
      'cat_investments': "Investimentos",
      'cat_taxes': "Impostos e Tributos",
      'cat_pet': "Pet",
      'cat_fixed_assets': "Imobilizado",
      'cat_other': "Outras Despesas",
      'inc_salary': "Salário",
      'inc_benefits': "Benefícios",
      'inc_other': "Outras Receitas",
      'sub_rent': "Aluguel Residência",
      'sub_condo': "Condomínio",
      'sub_water': "Água",
      'sub_electricity': "Luz (Eletricidade)",
      'sub_gas': "Gás",
      'sub_landline': "Telefone Fixo",
      'sub_internet': "Internet Residencial",
      'sub_home_insurance': "Seguro Residencial",
      'sub_maintenance': "Manutenção e Reparos",
      'sub_domestic_services': "Serviços Domésticos",
      'sub_cleaning': "Materiais de Limpeza",
      'sub_supermarket': "Supermercado",
      'sub_produce': "Sacolão/Hortifrúti",
      'sub_market': "Feira",
      'sub_restaurants': "Restaurantes/Bares",
      'sub_cafes': "Lanchonetes/Cafeterias",
      'sub_delivery': "Delivery e Aplicativos",
      'sub_vehicle_rent': "Financiamento/Aluguel de Veículo",
      'sub_fuel': "Combustível",
      'sub_public_transport': "Ônibus/Metrô/Aplicativos",
      'sub_vehicle_maintenance': "Manutenção do Veículo",
      'sub_vehicle_tax': "IPVA/Licenciamento",
      'sub_vehicle_insurance': "Seguro Auto",
      'sub_parking': "Estacionamento e Garagem",
      'sub_tolls': "Pedágios",
      'sub_fines': "Multas",
      'sub_health_plan': "Plano de Saúde",
      'sub_appointments': "Consultas Médicas",
      'sub_exams': "Exames",
      'sub_medicines': "Medicamentos",
      'sub_pharmacy': "Despesas com Farmácia/Drogaria",
      'sub_dentist': "Dentista/Odontologia",
      'sub_therapies': "Fisioterapia e Terapias",
      'sub_optics': "Ótica/Lentes/Óculos",
      'sub_medical_devices': "Aparelhos Auditivos/Ortopédicos",
      'sub_school': "Escola/Mensalidades",
      'sub_college': "Faculdade/Pós-graduação",
      'sub_courses': "Cursos Extracurriculares",
      'sub_supplies': "Material Escolar/Acessórios",
      'sub_books': "Livros e Publicações",
      'sub_online_courses': "Cursos Online e Plataformas",
      'sub_clothing': "Vestuário e Calçados",
      'sub_hygiene': "Higiene Pessoal",
      'sub_cosmetics': "Cosméticos e Maquiagem",
      'sub_salon': "Salão de Beleza/Cabeleireiro",
      'sub_barber': "Barbeiro",
      'sub_gym': "Academia e Atividades Esportivas",
      'sub_gifts': "Presentes",
      'sub_travel': "Viagens",
      'sub_hotels': "Hotéis e Pousadas",
      'sub_entertainment': "Cinema/Teatro/Shows",
      'sub_tickets': "Ingressos e Eventos",
      'sub_hobbies': "Hobbies e Coleções",
      'sub_clubs': "Mensalidades de Clubes/Associações",
      'sub_games': "Jogos e Assinaturas de Games",
      'sub_tv': "Plano de TV por Assinatura",
      'sub_streaming': "Netflix e Outras Plataformas",
      'sub_software': "Assinaturas de Software",
      'sub_cloud': "Armazenamento em Nuvem",
      'sub_credit_card_fee': "Cartão de Crédito (Anuidade)",
      'sub_loans': "Empréstimos e Financiamentos",
      'sub_bank_fees': "Tarifas Bancárias",
      'sub_insurance': "Seguros Diversos",
      'sub_consortium': "Consórcios",
      'sub_income_tax': "Imposto de Renda",
      'sub_property_tax': "IPTU",
      'sub_govt_fees': "Taxas Governamentais",
      'sub_pet_food': "Ração e Alimentação",
      'sub_vet': "Veterinário/Vacinas",
      'sub_pet_grooming': "Banho e Tosa",
      'sub_pet_toys': "Acessórios e Brinquedos",
      'sub_donations': "Doações/Caridade",
      'sub_unexpected': "Imprevistos",
      'sub_monthly_salary': "Salário Mensal",
      'sub_advance': "Adiantamento",
      'sub_13_salary': "13º Salário",
      'sub_vacation': "Férias",
      'sub_bonus': "Bônus/Comissões",
      'sub_meal_voucher': "Vale Alimentação/Refeição",
      'sub_transport_voucher': "Vale Transporte",
      'sub_home_office': "Auxílio Home Office",
      'sub_dividends': "Dividendos",
      'sub_jcp': "Juros sobre Capital Próprio",
      'sub_fixed_income': "Renda Fixa (CDB, Tesouro)",
      'sub_rent_received': "Aluguéis Recebidos",
      'sub_sale_assets': "Venda de Bens",
      'sub_refunds': "Reembolsos",
      
      // Fixed Assets
      'sub_appliances': "Eletrodomésticos",
      'sub_computer': "Computador",
      'sub_printer': "Impressora",
      'sub_mobile': "Celular",
      'sub_car': "Automóvel",
      'sub_furniture': "Móveis e utensilios",
      'sub_machines': "Máquinas",
      'sub_equipment': "Equipamento",
      
      // Recurrence
      'recurrence': "Recorrência",
      'recurrence_none': "Nenhum",
      'recurrence_daily': "Diário",
      'recurrence_weekly': "Semanal",
      'recurrence_monthly': "Mensal",
      'recurrence_yearly': "Anual",
    },
    'pt_PT': {
      // Home
      'app_title': 'FinAgeVoz',
      'subtitle': 'O seu assistente financeiro',
      'status_idle': "Toque para falar ou diga 'Finanças'",
      'status_listening': "A ouvir...",
      'status_processing': "A processar...",
      'hint_ok': "Diga \"OK\" para enviar",
      'hint_speak': "Fale o que quer e no final diga OK",
      'nav_finance': "Finanças",
      'nav_agenda': "Agenda",
      'nav_reports': "Relatórios",
      'nav_categories': "Categorias/Sub",
      
      // Status messages
      'status_tap_to_speak': "Toque para falar",
      'status_listening': "A ouvir...",
      'status_processing': "A processar...",
      
      // Menu
      'menu_settings': "Definições",
      'menu_help': "Ajuda",
      'menu_privacy': "Política de Privacidade",
      'menu_about': "Acerca",
      'menu_manage_data': "Gerir Dados",
      'menu_import_transactions': "Importar Transações (CSV)",
      'menu_import_calendar': "Importar Agenda (Google/Device)",
      'menu_export_transactions': "Exportar Transações (CSV)",
      'menu_export_calendar': "Exportar Agenda (Google/Device)",
      'select_calendar': "Selecione o Calendário",
      'select_calendar_dest': "Selecione o Calendário de Destino",
      'no_name': "Sem nome",
      'error_fetch_calendars': "Erro ao buscar calendários: ",
      'events_imported_success': " eventos importados com sucesso!",
      'no_new_events': "Nenhum evento novo encontrado.",
      'error_import_events': "Erro ao importar eventos: ",
      'error_export': "Erro ao exportar: ",
      'no_calendars_found': "Nenhum calendário encontrado ou permissão negada.",
      'transactions_imported_success': " transações importadas com sucesso!",
      'no_transactions_imported': "Nenhuma transação importada.",
      'error_import': "Erro ao importar: ",
      'transactions_count_label': "transações",
      'active_filters': "Filtros ativos: ",
      'filter_attachments': "Com Anexos",
      'filters_cleared': "Filtros limpos",
      'clear_filters': "Limpar Filtros",
      'share_report': "Partilhar Relatório",
      'transactions_report_title': "Relatório de Transações",
      'financial_report_title': "Relatório Financeiro",
      'events_report_title': "Relatório de Eventos",
      'apply_filters': "Aplicar Filtros",
      'period_custom': "Personalizado",
      'start_date': "Data Início",
      'end_date': "Data Fim",
      'select': "Selecionar",
      'categories_subcategories': "Categorias e Subcategorias",
      'categories_label': "Categorias:",
      'subcategories_label': "Subcategorias:",
      'value_range': "Intervalo de Valores",
      'min_value': "Valor Mínimo",
      'max_value': "Valor Máximo",
      'transaction_type': "Tipo de Transação",
      'installments': "Parceladas",
      'single_payments': "A Pronto",
      'exclude_reversals': "Excluir Estornos",
      'period_quarter': "Trimestre",
      'new_subcategory_title': "Nova Subcategoria em ",
      'export_csv': "Exportar CSV",
      'categories_exported_success': "Categorias exportadas com sucesso!",
      'google_drive': "Google Drive",
      'total_events': "Total de Eventos:",
      'active_events': "Ativos:",
      'cancelled_events': "Cancelados:",
      'active_events_title': "Eventos Ativos",
      'cancelled_events_title': "Eventos Cancelados",
      'table_time': "Hora",
      'table_location': "Local",
      'table_title': "Título",
      'calendar_error_not_found': "Nenhum calendário encontrado ou permissão negada.",
      'calendar_fetch_error': "Erro ao buscar calendários: ",
      'event_export_error': "Erro ao exportar eventos: ",
      'voice_commands_disabled_msg': "Os comandos de voz estão desativados nas definições.",
      'you_can_label': "Pode:",
      'voice_commands_note': "Nota: Comandos de voz requerem uma chave API Groq configurada.",
      'understood': "Entendi",
      'go_to_settings': "Ir para Definições",
      'voice_commands_setup_msg': "Para usar comandos de voz, precisa configurar uma chave API Groq.",
      'options_label': "Opções:",
      'get_key_at': "Obtenha a sua chave em: console.groq.com",
      'later': "Depois",
      'configure': "Configurar",
      'whatsapp_error': "Não foi possível abrir o WhatsApp.",
      'attachments_label': "Anexos",
      'delete_installment_msg': "Esta é uma transação parcelada. O que deseja fazer?",
      'delete_this': "Eliminar esta",
      'delete_all': "Eliminar todas",
      'cancelled_status': "Cancelado",
      'events_exported_success_suffix': " eventos exportados com sucesso!",
      'no_events_to_export': "Nenhum evento para exportar.",
      'mic_disabled': "Microfone desativado",
      'voice_commands_disabled_title': "ℹ️ Comandos de voz desativados",
      'manual_usage_option': "✓ Usar a app manualmente (botões e formulários)",
      'enable_voice_option': "✓ Ativar comandos de voz em:",
      'enable_voice_path': "  Menu → Definições → Ativar comandos de voz",
      'api_key_not_configured': "Chave API não configurada",
      'api_key_warning_title': "⚠️ Chave API não configurada",
      'configure_api_option': "1. Configure uma chave API gratuita",
      'disable_voice_option': "2. Desative comandos de voz e use a app manualmente",
      'period_label': "Período: ",
      'total_transactions': "Total Transações: ",
      'total_income': "Receitas: ",
      'total_expense': "Despesas: ",
      'balance_label': "Saldo: ",
      'table_date': "Data",
      'table_description': "Descrição",
      'table_category': "Categoria",
      'table_value': "Valor",
      'category_breakdown': "Detalhamento por Categoria",
      
      // Messages
      'msg_enable_voice': "Ative comandos de voz nas Definições para usar o microfone",
      'msg_configure_api': "Configure uma chave API nas Definições para usar comandos de voz",
      'about_title': "Acerca do FinAgeVoz",
      'about_version': "Versão 1.0.0",
      'about_description': "O seu assistente financeiro e de agenda inteligente.",
      'about_developed_by': "Desenvolvido por:",
      'about_company': "Multiverso Digital",
      'about_email_label': "E-mail:",
      'about_email': "contato@multiversodigita.com.br",
      
      // Help Dialog
      'help_title': "Comandos de Voz",
      'help_transactions': "💰 Transações:",
      'help_trans_1': "• \"Gastei 50 euros na padaria\"",
      'help_trans_2': "• \"Recebi 1000 euros de salário\"",
      'help_trans_3': "• \"Comprei TV de 2000 euros em 10x\"",
      'help_agenda': "📅 Agenda:",
      'help_agenda_1': "• \"Reunião amanhã às 14h\"",
      'help_agenda_2': "• \"Pagar luz dia 15\"",
      'help_attachments': "📎 Anexos e Partilha:",
      'help_attach_1': "• Adicione fotos e PDFs a transações e eventos.",
      'help_attach_2': "• Partilhe relatórios via WhatsApp.",
      'help_settings': "⚙️ Definições:",
      'help_settings_1': "• Controle se a aplicação fala os eventos ao abrir.",
      'help_settings_2': "• Faça a gestão de categorias e idioma.",
      'help_navigation': "📱 Navegação:",
      'help_nav_1': "• \"Abrir finanças\"",
      'help_nav_2': "• \"Abrir agenda\"",
      'help_nav_3': "• \"Ver relatórios\"",
      'help_tips': "💡 Dicas:",
      'help_tip_1': "• Fale naturalmente.",
      'help_tip_2': "• Aguarde o microfone pulsar.",
      'help_important': "⚠️ Importante:",
      'help_imp_1': "• O reconhecimento de voz requer internet.",
      'help_imp_2': "• Se o limite de dados da operadora for atingido, os comandos podem parar de funcionar.",
      'help_api_limit': "🔑 Limite de API:",
      'help_api_1': "• A aplicação usa inteligência artificial com limite diário gratuito.",
      'help_api_2': "• Se atingir o limite, aguarde algumas horas ou configure uma nova chave API.",
      'help_api_3': "• Aceda a Menu → Definições → Groq API Key para adicionar a sua própria chave.",
      'help_api_4': "• Obtenha uma chave gratuita em: console.groq.com",
      'help_recommendation': "💎 Recomendação para Uso Intenso:",
      'help_rec_1': "• Para até 100 transações/dia, recomendamos o plano pago Groq.",
      'help_rec_2': "• Modelo: Llama 3.3 70B Versatile",
      'help_rec_3': "• Custo: ~USD 10.35/mês (pay-as-you-go)",
      'help_rec_4': "• Sem limite diário, alta precisão e velocidade.",
      'menu_exit': "Sair",
      
      // Finance
      'finance_title': "Finanças",
      'balance_total': "Saldo Total",
      'income': "Receitas",
      'expenses': "Despesas",
      'filter_all': "Todos",
      'filter_income': "Receitas",
      'filter_expense': "Despesas",
      'add_transaction': "Adicionar Transação",
      'is_installment': "Parcelado?",
      'down_payment': "Valor da Entrada",
      'installment_count': "Nº de Parcelas",
      'installment_amount': "Valor da Parcela",
      'total_calculated': "Total Calculado: ",

      'empty_transactions': "Nenhuma transação encontrada.",
      'select_date': "Selecionar Data",
      'period_today': "Hoje",
      'period_week': "Esta Semana",
      'search_hint': "Pesquisar transações...",
      
      // Agenda
      'agenda_title': "Agenda",
      'empty_events': "Nenhum evento para este dia.",
      'search_hint_events': "Pesquisar eventos...",
      
      // Reports
      'reports_title': "Relatórios",
      'period_month': "Este Mês",
      'period_quarter': "Este Trimestre",
      'period_year': "Este Ano",
      'chart_income_expense': "Receitas vs Despesas",
      'chart_expenses_category': "Despesas por Categoria",
      'detailed_transactions': "Transações Detalhadas",
      'export_pdf': "Exportar PDF",
      'installments_report_title': "Relatório de Parcelas",
      'share_whatsapp': "Partilhar no WhatsApp",
      'error_share_pdf': "Erro ao partilhar PDF: ",
      'no_installments_found': "Nenhum parcelamento encontrado",
      'year_filter': "Ano: ",
      'month_filter': "Mês: ",
      'no_filtered_installments': "Nenhuma parcela encontrada com os filtros selecionados",
      'total_label': "Total: ",
      'advanced_filters': "Filtros Avançados",
      'view_installments': "Ver Parcelamentos",
      'share': "Partilhar",
      'clear': "Limpar",
      'period_quarter_short': "Trimestre",
      'period_year_short': "Ano",
      'period_last_7': "Últimos 7 dias",
      'period_last_30': "Últimos 30 dias",
      'period_last_90': "Últimos 90 dias",
      'categories_count': "categoria(s)",
      'subcategories_count': "subcategoria(s)",
      'filtered_values': "Valores filtrados",
      'no_expenses': "sem despesas",
      'no_income': "sem receitas",
      'no_installments': "sem parceladas",
      'no_single_payments': "sem à vista",
      
      // Categories
      'categories_title': "Categorias",
      'tab_expense': "Despesas",
      'tab_income': "Receitas",
      'add_category': "Nova Categoria",
      'edit_category': "Editar Categoria",
      'delete_category': "Eliminar Categoria",
      'confirm_delete': "Tem a certeza que deseja eliminar?",
      'cancel': "Cancelar",
      'save': "Guardar",
      'delete': "Eliminar",
      'name': "Nome",
      'amount': "Valor",
      'date': "Data",
      'category': "Categoria",
      'subcategory': "Subcategoria",
      'type': "Tipo",
      'description': "Descrição",
      'close': "Fechar",
      'delete_transaction': "Eliminar Transação",
      'delete_event': "Eliminar Evento",
      'expense': "Despesa",
      'no_transactions': "Nenhuma transação encontrada",
      'no_events': "Nenhum evento encontrado",
      'transfer': "Transferir",
      'cancel_event': "Cancelar",
      'reactivate': "Reativar",
      'reverse': "Estornar",
      'edit': "Editar",
      'confirm_reverse': "Confirmar estorno de",
      'reversal_of': "Estorno de",
      'is_expense': "É despesa?",
      'invalid_data': "Dados inválidos",
      'pdf_generated': "PDF gerado com sucesso!",
      'error': "Erro",
      'data_management': "Gerir Dados",
      'database_statistics': "Estatísticas da Base de Dados",
      'transactions': "transações",
      'events': "eventos",
      'categories': "categorias",
      'sign_in': "Entrar",
      'sign_out': "Sair",
      'signed_in_as': "Conectado como",
      'backup_and_clean': "Cópia de Segurança e Limpeza",
      'clean_data_older_than': "Limpar dados anteriores a",
      '6_months': "6 meses",
      '1_year': "1 ano",
      '2_years': "2 anos",
      'backup_and_clean_button': "Fazer Cópia e Limpar",
      'available_backups': "Cópias Disponíveis",
      'no_backups': "Nenhuma cópia encontrada",
      'restore': "Restaurar",
      'confirm_backup_clean': "Confirmar Cópia e Limpeza",
      'confirm_backup_clean_message': "Os dados antigos serão guardados no Google Drive e depois removidos do dispositivo. Deseja continuar?",
      'continue': "Continuar",
      'google_signin_failed': "Falha ao fazer login no Google",
      'backup_success': "Cópia realizada com sucesso",
      'confirm_restore': "Confirmar Restauração",
      'confirm_restore_message': "Os dados da cópia serão importados. Deseja continuar?",
      'restore_success': "Dados restaurados com sucesso",
      'database_size': "Tamanho da Base de Dados",
      'of_max_size': "do tamanho máximo",
      'quick_access': "ACESSO RÁPIDO",

      'no_categories': "Nenhuma categoria encontrada",
      'no_subcategories': "Nenhuma subcategoria",
      'status': "Estado",
      'cancelled': "Cancelado",
      'danger_zone': "Zona de Perigo",
      'wipe_all_data': "Apagar TODOS os Dados",
      
      // Settings / Onboarding
      'settings_title': "Definições",
      'onboarding_title': "Configuração Inicial",
      'wake_word_label': "Palavra de Ativação",
      'wake_word_hint': "Ex: Jarvis",
      'language_label': "Idioma / Language",
      'groq_label': "Groq AI (Opcional)",
      'groq_desc': "Para uma resposta muito mais rápida, use a Groq.",
      'groq_hint': "gsk_...",
      'save_continue': "Guardar e Continuar",
      'save_btn': "Guardar",
      'error_password': "Por favor, defina uma palavra de ativação.",
      'saved_settings': "Definições guardadas!",
      'classify_transaction': "Classificar Transação",
      'policy_title': "Política de Privacidade",
      'about_title': "Acerca",
      'version_label': "Versão",
      'developed_by': "Desenvolvido por:",
      'contact_label': "Contacto:",
      'help_usage_title': "Como usar o FinAgeVoz",
      'important_label': "Importante:",
      'command_examples_label': "Exemplos de Comandos:",
      'understood_btn': "Entendi",
      'help_tooltip': "Ajuda",
      'categories_tooltip': "Categorias",
      'error_pdf_gen': "Erro ao gerar PDF",
      'get_groq_key_title': "Obter Chave Groq",
      'no_key_link': "Não tem uma chave? Clique aqui",
      'how_to_get_key_tooltip': "Como obter a chave?",
      'mic_init_error': "Erro ao iniciar microfone. Tente novamente.",
      'category_name_label': "Nome",
      'category_desc_label': "Descrição",
      'subcategory_name_label': "Nome da Subcategoria",
      'add_subcategory_tooltip': "Adicionar Subcategoria",
      'delete_category_error': "Não é possível eliminar categoria com transações associadas.",
      'groq_api_key_label': "Chave da API Groq",
      'settings_general': "Geral",
      'settings_announce_events': "Sempre anunciar eventos",
      'settings_announce_events_desc': "Falar eventos ao abrir a aplicação mesmo se já ditos",
      'settings_enable_voice': "Ativar comandos de voz",
      'settings_enable_voice_desc': "Usar IA para processar comandos de voz",
      'voice_enabled_msg': "Comandos de voz ativados. Reinicie a aplicação para aplicar.",
      'voice_disabled_msg': "Comandos de voz desativados. Use a aplicação manualmente.",
      'settings_data': "Dados",
      'settings_reset_categories': "Repor Categorias",
      'settings_reset_categories_desc': "Restaura as categorias padrão",
      'settings_reset_app': "Repor Aplicação (Apagar Tudo)",
      'settings_reset_app_desc': "Apaga todas as transações e eventos",
      'settings_api_title': "API para Comandos de Voz",
      'settings_api_in_use': "API em uso:",
      'settings_no_api': "Nenhuma API configurada",
      'settings_configured': "Configurada",
      'settings_not_configured': "Não configurada",
      'how_to_get_key_title': "Como obter a sua chave Groq API:",
      'get_key_step_1': "1. Aceda a: console.groq.com",
      'get_key_step_2': "2. Faça login ou crie uma conta gratuita",
      'get_key_step_3': "3. Vá a \"API Keys\" no menu lateral",
      'get_key_step_4': "4. Clique em \"Create API Key\"",
      'get_key_step_5': "5. Copie a chave gerada (começa com \"gsk_\")",
      'paste_key_below': "Cole a sua chave abaixo:",
      'api_key_label': "Chave API",
      'api_key_helper': "Obrigatório para usar a aplicação",
      'api_key_updated': "Chave API atualizada!",
      'confirm_reset_categories_title': "Repor Categorias?",
      'confirm_reset_categories_msg': "Isto irá restaurar as categorias originais. Categorias personalizadas não serão afetadas, mas nomes padrão serão repostos para o idioma atual.",
      'reset': "Repor",
      'categories_reset_success': "Categorias repostas com sucesso!",
      'confirm_wipe_title': "Apagar TUDO?",
      'confirm_wipe_msg': "Tem a certeza que deseja apagar TODAS as transações e eventos? Esta ação não pode ser desfeita.",
      'wipe_all': "Apagar TUDO",
      'data_wiped_msg': "Dados apagados: {transactions} transações, {events} eventos.",
      'error_prefix': "Erro: ",
      'language_changed_msg': "Idioma alterado. Reinicie a aplicação para aplicar em todos os ecrãs.",
      
      // Categories & Subcategories (same as pt_BR but with PT adaptations)
      'cat_housing': "Habitação",
      'cat_food': "Alimentação",
      'cat_transport': "Transporte",
      'cat_health': "Saúde",
      'cat_education': "Educação",
      'cat_personal': "Despesas Pessoais",
      'cat_leisure': "Lazer",
      'cat_subscriptions': "Subscrições e Serviços Digitais",
      'cat_financial': "Serviços Financeiros",
      'cat_investments': "Investimentos",
      'cat_taxes': "Impostos e Tributos",
      'cat_pet': "Animais de Estimação",
      'cat_fixed_assets': "Imobilizado",
      'cat_other': "Outras Despesas",
      'inc_salary': "Salário",
      'inc_benefits': "Benefícios",
      'inc_other': "Outras Receitas",
      'sub_rent': "Renda de Residência",
      'sub_condo': "Condomínio",
      'sub_water': "Água",
      'sub_electricity': "Eletricidade",
      'sub_gas': "Gás",
      'sub_landline': "Telefone Fixo",
      'sub_internet': "Internet Residencial",
      'sub_home_insurance': "Seguro Residencial",
      'sub_maintenance': "Manutenção e Reparos",
      'sub_domestic_services': "Serviços Domésticos",
      'sub_cleaning': "Materiais de Limpeza",
      'sub_supermarket': "Supermercado",
      'sub_produce': "Hortifrúti",
      'sub_market': "Feira",
      'sub_restaurants': "Restaurantes/Bares",
      'sub_cafes': "Cafés/Cafetarias",
      'sub_delivery': "Entregas e Aplicações",
      'sub_vehicle_rent': "Financiamento/Aluguer de Veículo",
      'sub_fuel': "Combustível",
      'sub_public_transport': "Autocarro/Metro/Aplicações",
      'sub_vehicle_maintenance': "Manutenção do Veículo",
      'sub_vehicle_tax': "Imposto Automóvel/Licenciamento",
      'sub_vehicle_insurance': "Seguro Automóvel",
      'sub_parking': "Estacionamento e Garagem",
      'sub_tolls': "Portagens",
      'sub_fines': "Multas",
      'sub_health_plan': "Plano de Saúde",
      'sub_appointments': "Consultas Médicas",
      'sub_exams': "Exames",
      'sub_medicines': "Medicamentos",
      'sub_pharmacy': "Despesas com Farmácia",
      'sub_dentist': "Dentista/Odontologia",
      'sub_therapies': "Fisioterapia e Terapias",
      'sub_optics': "Ótica/Lentes/Óculos",
      'sub_medical_devices': "Aparelhos Auditivos/Ortopédicos",
      'sub_school': "Escola/Mensalidades",
      'sub_college': "Faculdade/Pós-graduação",
      'sub_courses': "Cursos Extracurriculares",
      'sub_supplies': "Material Escolar/Acessórios",
      'sub_books': "Livros e Publicações",
      'sub_online_courses': "Cursos Online e Plataformas",
      'sub_clothing': "Vestuário e Calçado",
      'sub_hygiene': "Higiene Pessoal",
      'sub_cosmetics': "Cosméticos e Maquilhagem",
      'sub_salon': "Cabeleireiro",
      'sub_barber': "Barbeiro",
      'sub_gym': "Ginásio e Atividades Desportivas",
      'sub_gifts': "Presentes",
      'sub_travel': "Viagens",
      'sub_hotels': "Hotéis e Pousadas",
      'sub_entertainment': "Cinema/Teatro/Espetáculos",
      'sub_tickets': "Bilhetes e Eventos",
      'sub_hobbies': "Hobbies e Coleções",
      'sub_clubs': "Mensalidades de Clubes/Associações",
      'sub_games': "Jogos e Subscrições de Jogos",
      'sub_tv': "Plano de TV por Subscrição",
      'sub_streaming': "Netflix e Outras Plataformas",
      'sub_software': "Subscrições de Software",
      'sub_cloud': "Armazenamento na Nuvem",
      'sub_credit_card_fee': "Cartão de Crédito (Anuidade)",
      'sub_loans': "Empréstimos e Financiamentos",
      'sub_bank_fees': "Tarifas Bancárias",
      'sub_insurance': "Seguros Diversos",
      'sub_consortium': "Consórcios",
      'sub_income_tax': "IRS",
      'sub_property_tax': "IMI",
      'sub_govt_fees': "Taxas Governamentais",
      'sub_pet_food': "Ração e Alimentação",
      'sub_vet': "Veterinário/Vacinas",
      'sub_pet_grooming': "Banho e Tosquia",
      'sub_pet_toys': "Acessórios e Brinquedos",
      'sub_donations': "Doações/Caridade",
      'sub_vacation': "Férias",
      'sub_bonus': "Bónus/Comissões",
      'sub_meal_voucher': "Vale de Alimentação/Refeição",
      'sub_transport_voucher': "Vale de Transporte",
      'sub_home_office': "Auxílio Teletrabalho",
      'sub_dividends': "Dividendos",
      'sub_jcp': "Juros sobre Capital Próprio",
      'sub_fixed_income': "Renda Fixa",
      'sub_rent_received': "Rendas Recebidas",
      'sub_sale_assets': "Venda de Bens",
      'sub_refunds': "Reembolsos",
      
      // Fixed Assets
      'sub_appliances': "Eletrodomésticos",
      'sub_computer': "Computador",
      'sub_printer': "Impressora",
      'sub_smartphone': "Smartphone",
      'sub_tablet': "Tablet",
      'sub_tv': "Televisão",
      'sub_furniture': "Mobiliário",
      'sub_tools': "Ferramentas",
      
      // Recurrence
      'recurrence_daily': "Diário",
      'recurrence_weekly': "Semanal",
      'recurrence_monthly': "Mensal",
      'recurrence_yearly': "Anual",
    },
    'en': {
      'nav_finance': "Finance",
      'nav_agenda': "Agenda",
      'nav_reports': "Reports",
      'nav_categories': "Categories/Sub",
      
      // Home
      'app_title': 'FinAgeVoz',
      'subtitle': 'Your financial assistant',
      
      // Status messages
      'status_tap_to_speak': "Tap to speak",
      'status_listening': "Listening...",
      'status_processing': "Processing...",
      
      // Menu
      'menu_settings': "Settings",
      'menu_help': "Help",
      'menu_privacy': "Privacy Policy",
      'menu_about': "About",
      'menu_manage_data': "Manage Data",
      'menu_import_transactions': "Import Transactions (CSV)",
      'menu_import_calendar': "Import Calendar (Google/Device)",
      'menu_export_transactions': "Export Transactions (CSV)",
      'menu_export_calendar': "Export Calendar (Google/Device)",
      'select_calendar': "Select Calendar",
      'select_calendar_dest': "Select Destination Calendar",
      'no_name': "No name",
      'error_fetch_calendars': "Error fetching calendars: ",
      'events_imported_success': " events imported successfully!",
      'no_new_events': "No new events found.",
      'error_import_events': "Error importing events: ",
      'error_export': "Error exporting: ",
      'no_calendars_found': "No calendars found or permission denied.",
      'transactions_imported_success': " transactions imported successfully!",
      'no_transactions_imported': "No transactions imported.",
      'error_import': "Error importing: ",
      'transactions_count_label': "transactions",
      'active_filters': "Active filters: ",
      'filter_attachments': "With Attachments",
      'filters_cleared': "Filters cleared",
      'clear_filters': "Clear Filters",
      'share_report': "Share Report",
      'transactions_report_title': "Transactions Report",
      'financial_report_title': "Financial Report",
      'events_report_title': "Events Report",
      'apply_filters': "Apply Filters",
      'period_custom': "Custom",
      'start_date': "Start Date",
      'end_date': "End Date",
      'select': "Select",
      'categories_subcategories': "Categories and Subcategories",
      'categories_label': "Categories:",
      'subcategories_label': "Subcategories:",
      'value_range': "Value Range",
      'min_value': "Min Value",
      'max_value': "Max Value",
      'transaction_type': "Transaction Type",
      'installments': "Installments",
      'single_payments': "Single Payments",
      'exclude_reversals': "Exclude Reversals",
      'period_quarter': "Quarter",
      'new_subcategory_title': "New Subcategory in ",
      'export_csv': "Export CSV",
      'categories_exported_success': "Categories exported successfully!",
      'google_drive': "Google Drive",
      'total_events': "Total Events:",
      'active_events': "Active:",
      'cancelled_events': "Cancelled:",
      'active_events_title': "Active Events",
      'cancelled_events_title': "Cancelled Events",
      'table_time': "Time",
      'table_location': "Location",
      'table_title': "Title",
      'calendar_error_not_found': "No calendar found or permission denied.",
      'calendar_fetch_error': "Error fetching calendars: ",
      'event_export_error': "Error exporting events: ",
      'voice_commands_disabled_msg': "Voice commands are disabled in settings.",
      'you_can_label': "You can:",
      'voice_commands_note': "Note: Voice commands require a configured Groq API key.",
      'understood': "Understood",
      'go_to_settings': "Go to Settings",
      'voice_commands_setup_msg': "To use voice commands, you need to configure a Groq API key.",
      'options_label': "Options:",
      'get_key_at': "Get your key at: console.groq.com",
      'later': "Later",
      'configure': "Configure",
      'whatsapp_error': "Could not open WhatsApp.",
      'attachments_label': "Attachments",
      'delete_installment_msg': "This is an installment transaction. What do you want to do?",
      'delete_this': "Delete this",
      'delete_all': "Delete all",
      'cancelled_status': "Cancelled",
      'events_exported_success_suffix': " events exported successfully!",
      'no_events_to_export': "No events to export.",
      'mic_disabled': "Microphone disabled",
      'voice_commands_disabled_title': "ℹ️ Voice commands disabled",
      'manual_usage_option': "✓ Use app manually (buttons and forms)",
      'enable_voice_option': "✓ Enable voice commands in:",
      'enable_voice_path': "  Menu → Settings → Enable voice commands",
      'api_key_not_configured': "API Key not configured",
      'api_key_warning_title': "⚠️ API Key not configured",
      'configure_api_option': "1. Configure a free API key",
      'disable_voice_option': "2. Disable voice commands and use app manually",
      'period_label': "Period: ",
      'total_transactions': "Total Transactions: ",
      'total_income': "Income: ",
      'total_expense': "Expenses: ",
      'balance_label': "Balance: ",
      'table_date': "Date",
      'table_description': "Description",
      'table_category': "Category",
      'table_value': "Amount",
      'category_breakdown': "Breakdown by Category",
      
      // Messages
      'msg_enable_voice': "Enable voice commands in Settings to use the microphone",
      'msg_configure_api': "Configure an API key in Settings to use voice commands",
      'about_title': "About FinAgeVoz",
      'about_version': "Version 1.0.0",
      'about_description': "Your intelligent financial and calendar assistant.",
      'about_developed_by': "Developed by:",
      'about_company': "Multiverso Digital",
      'about_email_label': "Email:",
      'about_email': "contato@multiversodigita.com.br",
      
      // Help Dialog
      'help_title': "Voice Commands",
      'help_transactions': "💰 Transactions:",
      'help_trans_1': "• \"I spent 50 dollars at the bakery\"",
      'help_trans_2': "• \"I received 1000 dollars salary\"",
      'help_trans_3': "• \"Bought TV for 2000 dollars in 10 installments\"",
      'help_agenda': "📅 Calendar:",
      'help_agenda_1': "• \"Meeting tomorrow at 2pm\"",
      'help_agenda_2': "• \"Pay electricity bill on the 15th\"",
      'help_attachments': "📎 Attachments and Sharing:",
      'help_attach_1': "• Add photos and PDFs to transactions and events.",
      'help_attach_2': "• Share reports via WhatsApp.",
      'help_settings': "⚙️ Settings:",
      'help_settings_1': "• Control if the app speaks events on startup.",
      'help_settings_2': "• Manage categories and language.",
      'help_navigation': "📱 Navigation:",
      'help_nav_1': "• \"Open finance\"",
      'help_nav_2': "• \"Open calendar\"",
      'help_nav_3': "• \"View reports\"",
      'help_tips': "💡 Tips:",
      'help_tip_1': "• Speak naturally.",
      'help_tip_2': "• Wait for the microphone to pulse.",
      'help_important': "⚠️ Important:",
      'help_imp_1': "• Voice recognition requires internet.",
      'help_imp_2': "• If carrier data limit is reached, commands may stop working.",
      'help_api_limit': "🔑 API Limit:",
      'help_api_1': "• The app uses AI with a free daily limit.",
      'help_api_2': "• If you reach the limit, wait a few hours or configure a new API key.",
      'help_api_3': "• Go to Menu → Settings → Groq API Key to add your own key.",
      'help_api_4': "• Get a free key at: console.groq.com",
      'help_recommendation': "💎 Recommendation for Heavy Use:",
      'help_rec_1': "• For up to 100 transactions/day, we recommend Groq's paid plan.",
      'help_rec_2': "• Model: Llama 3.3 70B Versatile",
      'help_rec_3': "• Cost: ~USD 10.35/month (pay-as-you-go)",
      'help_rec_4': "• No daily limit, high accuracy and speed.",
      'menu_exit': "Exit",
      
      // Finance
      'finance_title': "Finance",
      'balance_total': "Total Balance",
      'income': "Income",
      'expenses': "Expenses",
      'filter_all': "All",
      'filter_income': "Income",
      'filter_expense': "Expenses",
      'add_transaction': "Add Transaction",
      'is_installment': "Installments?",
      'down_payment': "Down Payment",
      'installment_count': "Number of Installments",
      'installment_amount': "Installment Amount",
      'total_calculated': "Calculated Total: ",
      'empty_transactions': "No transactions found.",
      'select_date': "Select Date",
      'period_today': "Today",
      'period_week': "This Week",
      'search_hint': "Search transactions...",
      
      // Agenda
      'agenda_title': "Agenda",
      'empty_events': "No events for this day.",
      'search_hint_events': "Search events...",
      
      // Reports
      'reports_title': "Reports",
      'period_month': "This Month",
      'period_quarter': "This Quarter",
      'period_year': "This Year",
      'chart_income_expense': "Income vs Expenses",
      'chart_expenses_category': "Expenses by Category",
      'detailed_transactions': "Detailed Transactions",
      'export_pdf': "Export PDF",
      'installments_report_title': "Installments Report",
      'share_whatsapp': "Share on WhatsApp",
      'error_share_pdf': "Error sharing PDF: ",
      'no_installments_found': "No installments found",
      'year_filter': "Year: ",
      'month_filter': "Month: ",
      'no_filtered_installments': "No installments found with selected filters",
      'total_label': "Total: ",
      'advanced_filters': "Advanced Filters",
      'view_installments': "View Installments",
      'share': "Share",
      'clear': "Clear",
      'period_quarter_short': "Quarter",
      'period_year_short': "Year",
      'period_last_7': "Last 7 days",
      'period_last_30': "Last 30 days",
      'period_last_90': "Last 90 days",
      'categories_count': "category(s)",
      'subcategories_count': "subcategory(s)",
      'filtered_values': "Filtered values",
      'no_expenses': "no expenses",
      'no_income': "no income",
      'no_installments': "no installments",
      'no_single_payments': "no single payments",
      
      // Categories
      'categories_title': "Categories",
      'tab_expense': "Expenses",
      'tab_income': "Income",
      'add_category': "New Category",
      'edit_category': "Edit Category",
      'delete_category': "Delete Category",
      'confirm_delete': "Are you sure you want to delete?",
      'cancel': "Cancel",
      'save': "Save",
      'delete': "Delete",
      'name': "Name",
      
      // Settings / Onboarding
      'settings_title': "Settings",
      'onboarding_title': "Initial Setup",
      'wake_word_label': "Voice Password",
      'wake_word_hint': "Ex: Jarvis",
      'language_label': "Language",
      'groq_label': "Groq AI (Optional)",
      'groq_desc': "For much faster response, use Groq.",
      'groq_hint': "gsk_...",
      'save_continue': "Save and Continue",
      'save_btn': "Save",
      'error_password': "Please set a voice password.",
      'saved_settings': "Settings saved!",
      'classify_transaction': "Classify Transaction",
      'policy_title': "Privacy Policy",
      'about_title': "About",
      'version_label': "Version",
      'developed_by': "Developed by:",
      'contact_label': "Contact:",
      'help_usage_title': "How to use FinAgeVoz",
      'important_label': "Important:",
      'command_examples_label': "Command Examples:",
      'understood_btn': "Understood",
      'help_tooltip': "Help",
      'categories_tooltip': "Categories",
      'error_pdf_gen': "Error generating PDF",
      'get_groq_key_title': "Get Groq Key",
      'no_key_link': "Don't have a key? Click here",
      'how_to_get_key_tooltip': "How to get key?",
      'mic_init_error': "Error initializing microphone. Try again.",
      'category_name_label': "Name",
      'category_desc_label': "Description",
      'subcategory_name_label': "Subcategory Name",
      'add_subcategory_tooltip': "Add Subcategory",
      'delete_category_error': "Cannot delete category with associated transactions.",
      'groq_api_key_label': "Groq API Key",
      'settings_general': "General",
      'settings_announce_events': "Always announce events",
      'settings_announce_events_desc': "Speak events when opening app even if already spoken",
      'settings_enable_voice': "Enable voice commands",
      'settings_enable_voice_desc': "Use AI to process voice commands",
      'voice_enabled_msg': "Voice commands enabled. Restart app to apply.",
      'voice_disabled_msg': "Voice commands disabled. Use app manually.",
      'settings_data': "Data",
      'settings_reset_categories': "Reset Categories",
      'settings_reset_categories_desc': "Restores default categories",
      'settings_reset_app': "Reset App (Wipe All)",
      'settings_reset_app_desc': "Deletes all transactions and events",
      'settings_api_title': "Voice Command API",
      'settings_api_in_use': "API in use:",
      'settings_no_api': "No API configured",
      'settings_configured': "Configured",
      'settings_not_configured': "Not configured",
      'how_to_get_key_title': "How to get your Groq API key:",
      'get_key_step_1': "1. Go to: console.groq.com",
      'get_key_step_2': "2. Login or create free account",
      'get_key_step_3': "3. Go to \"API Keys\" in side menu",
      'get_key_step_4': "4. Click \"Create API Key\"",
      'get_key_step_5': "5. Copy generated key (starts with \"gsk_\")",
      'paste_key_below': "Paste your key below:",
      'api_key_label': "API Key",
      'api_key_helper': "Required to use the app",
      'api_key_updated': "API Key updated!",
      'confirm_reset_categories_title': "Reset Categories?",
      'confirm_reset_categories_msg': "This will restore original categories. Custom categories won't be affected, but default names will be reset to current language.",
      'reset': "Reset",
      'categories_reset_success': "Categories reset successfully!",
      'confirm_wipe_title': "Wipe ALL?",
      'confirm_wipe_msg': "Are you sure you want to delete ALL transactions and events? This cannot be undone.",
      'wipe_all': "Wipe ALL",
      'data_wiped_msg': "Data wiped: {transactions} transactions, {events} events.",
      'error_prefix': "Error: ",
      'language_changed_msg': "Language changed. Restart app to apply everywhere.",
      'danger_zone': "Danger Zone",
      'wipe_all_data': "Wipe ALL Data",

      // Categories & Subcategories
      'cat_housing': "Housing",
      'cat_food': "Food",
      'cat_transport': "Transport",
      'cat_health': "Health",
      'cat_education': "Education",
      'cat_personal': "Personal Expenses",
      'cat_leisure': "Leisure",
      'cat_subscriptions': "Subscriptions & Digital Services",
      'cat_financial': "Financial Services",
      'cat_investments': "Investments",
      'cat_taxes': "Taxes",
      'cat_pet': "Pet",
      'cat_fixed_assets': "Fixed Assets",
      'cat_other': "Other Expenses",
      'inc_salary': "Salary",
      'inc_benefits': "Benefits",
      'inc_other': "Other Income",
      'sub_rent': "Rent",
      'sub_condo': "Condo Fee",
      'sub_water': "Water",
      'sub_electricity': "Electricity",
      'sub_gas': "Gas",
      'sub_landline': "Landline",
      'sub_internet': "Internet",
      'sub_home_insurance': "Home Insurance",
      'sub_maintenance': "Maintenance & Repairs",
      'sub_domestic_services': "Domestic Services",
      'sub_cleaning': "Cleaning Supplies",
      'sub_supermarket': "Supermarket",
      'sub_produce': "Produce/Market",
      'sub_market': "Farmers Market",
      'sub_restaurants': "Restaurants/Bars",
      'sub_cafes': "Cafes/Snacks",
      'sub_delivery': "Delivery & Apps",
      'sub_vehicle_rent': "Vehicle Financing/Rent",
      'sub_fuel': "Fuel",
      'sub_public_transport': "Public Transport",
      'sub_vehicle_maintenance': "Vehicle Maintenance",
      'sub_vehicle_tax': "Vehicle Tax",
      'sub_vehicle_insurance': "Car Insurance",
      'sub_parking': "Parking",
      'sub_tolls': "Tolls",
      'sub_fines': "Fines",
      'sub_health_plan': "Health Plan",
      'sub_appointments': "Medical Appointments",
      'sub_exams': "Exams",
      'sub_medicines': "Medicines",
      'sub_pharmacy': "Pharmacy",
      'sub_dentist': "Dentist",
      'sub_therapies': "Therapies",
      'sub_optics': "Optics/Glasses",
      'sub_medical_devices': "Medical Devices",
      'sub_school': "School/Tuition",
      'sub_college': "College/Grad School",
      'sub_courses': "Extracurricular Courses",
      'sub_supplies': "School Supplies",
      'sub_books': "Books",
      'sub_online_courses': "Online Courses",
      'sub_clothing': "Clothing & Shoes",
      'sub_hygiene': "Personal Hygiene",
      'sub_cosmetics': "Cosmetics & Makeup",
      'sub_salon': "Beauty Salon",
      'sub_barber': "Barber",
      'sub_gym': "Gym & Sports",
      'sub_gifts': "Gifts",
      'sub_travel': "Travel",
      'sub_hotels': "Hotels",
      'sub_entertainment': "Cinema/Theater/Shows",
      'sub_tickets': "Tickets & Events",
      'sub_hobbies': "Hobbies",
      'sub_clubs': "Club Memberships",
      'sub_games': "Games & Subscriptions",
      'sub_tv': "TV Subscription",
      'sub_streaming': "Netflix & Streaming",
      'sub_software': "Software Subscriptions",
      'sub_cloud': "Cloud Storage",
      'sub_credit_card_fee': "Credit Card Fee",
      'sub_loans': "Loans",
      'sub_bank_fees': "Bank Fees",
      'sub_insurance': "Insurance",
      'sub_consortium': "Consortium",
      'sub_income_tax': "Income Tax",
      'sub_property_tax': "Property Tax",
      'sub_govt_fees': "Government Fees",
      'sub_pet_food': "Pet Food",
      'sub_vet': "Vet/Vaccines",
      'sub_pet_grooming': "Grooming",
      'sub_pet_toys': "Toys & Accessories",
      'sub_donations': "Donations/Charity",
      'sub_unexpected': "Unexpected",
      'sub_monthly_salary': "Monthly Salary",
      'sub_advance': "Salary Advance",
      'sub_13_salary': "13th Salary",
      'sub_vacation': "Vacation Pay",
      'sub_bonus': "Bonus/Commissions",
      'sub_meal_voucher': "Meal Voucher",
      'sub_transport_voucher': "Transport Voucher",
      'sub_home_office': "Home Office Aid",
      'sub_dividends': "Dividends",
      'sub_jcp': "Interest on Equity",
      'sub_fixed_income': "Fixed Income",
      'sub_rent_received': "Rent Received",
      'sub_sale_assets': "Sale of Assets",
      'sub_refunds': "Refunds",

      // Fixed Assets
      'sub_appliances': "Appliances",
      'sub_computer': "Computer",
      'sub_printer': "Printer",
      'sub_mobile': "Mobile Phone",
      'sub_car': "Automobile",
      'sub_furniture': "Furniture & Utensils",
      'sub_machines': "Machines",
      'sub_equipment': "Equipment",

      // Recurrence
      'recurrence': "Recurrence",
      'recurrence_none': "None",
      'recurrence_daily': "Daily",
      'recurrence_weekly': "Weekly",
      'recurrence_monthly': "Monthly",
      'recurrence_yearly': "Yearly",
      'add_event': "Add Event",
      'edit_event': "Edit Event",
      'title': "Title",
      'required_field': "Required field",
      'sub_cash_gifts': "Cash Gifts",
    },
    'es': {
      // Home
      'app_title': 'FinAgeVoz',
      'subtitle': 'Su asistente financiero',
      'status_idle': "Toque para hablar o diga 'Finanzas'",
      'status_listening': "Escuchando...",
      'status_processing': "Procesando...",
      'hint_ok': "Diga \"OK\" para enviar",
      'hint_speak': "Diga lo que quiere y al final diga OK",
      'nav_finance': "Finanzas",
      'nav_agenda': "Agenda",
      'nav_reports': "Informes",
      'nav_categories': "Categorías/Sub",
      
      // Status messages
      'status_tap_to_speak': "Toque para hablar",
      
      // Menu
      'menu_settings': "Configuración",
      'menu_help': "Ayuda",
      'menu_privacy': "Política de Privacidad",
      'menu_about': "Acerca de",
      'menu_manage_data': "Administrar Datos",
      'menu_import_transactions': "Importar Transacciones (CSV)",
      'menu_import_calendar': "Importar Calendario (Google/Device)",
      'menu_export_transactions': "Exportar Transacciones (CSV)",
      'menu_export_calendar': "Exportar Calendario (Google/Device)",
      'select_calendar': "Seleccionar Calendario",
      'select_calendar_dest': "Seleccionar Calendario de Destino",
      'no_name': "Sin nombre",
      'error_fetch_calendars': "Error al obtener calendarios: ",
      'events_imported_success': " eventos importados con éxito!",
      'no_new_events': "No se encontraron eventos nuevos.",
      'error_import_events': "Error al importar eventos: ",
      'error_export': "Error al exportar: ",
      'no_calendars_found': "No se encontraron calendarios o permiso denegado.",
      'transactions_imported_success': " transacciones importadas con éxito!",
      'no_transactions_imported': "Ninguna transacción importada.",
      'error_import': "Error al importar: ",
      'transactions_count_label': "transacciones",
      'active_filters': "Filtros activos: ",
      'filter_attachments': "Con Adjuntos",
      'filters_cleared': "Filtros limpiados",
      'clear_filters': "Limpiar Filtros",
      'share_report': "Compartir Informe",
      'transactions_report_title': "Informe de Transacciones",
      'financial_report_title': "Informe Financiero",
      'events_report_title': "Informe de Eventos",
      'apply_filters': "Aplicar Filtros",
      'period_custom': "Personalizado",
      'start_date': "Fecha Inicio",
      'end_date': "Fecha Fin",
      'select': "Seleccionar",
      'categories_subcategories': "Categorías y Subcategorías",
      'categories_label': "Categorías:",
      'subcategories_label': "Subcategorías:",
      'value_range': "Rango de Valores",
      'min_value': "Valor Mínimo",
      'max_value': "Valor Máximo",
      'transaction_type': "Tipo de Transacción",
      'installments': "Cuotas",
      'single_payments': "Al Contado",
      'exclude_reversals': "Excluir Reembolsos",
      'period_quarter': "Trimestre",
      'new_subcategory_title': "Nueva Subcategoría en ",
      'export_csv': "Exportar CSV",
      'categories_exported_success': "¡Categorías exportadas con éxito!",
      'google_drive': "Google Drive",
      'total_events': "Total Eventos:",
      'active_events': "Activos:",
      'cancelled_events': "Cancelados:",
      'active_events_title': "Eventos Activos",
      'cancelled_events_title': "Eventos Cancelados",
      'table_time': "Hora",
      'table_location': "Ubicación",
      'table_title': "Título",
      'calendar_error_not_found': "No se encontró ningún calendario o permiso denegado.",
      'calendar_fetch_error': "Error al buscar calendarios: ",
      'event_export_error': "Error al exportar eventos: ",
      'voice_commands_disabled_msg': "Los comandos de voz están desactivados en la configuración.",
      'you_can_label': "Puedes:",
      'voice_commands_note': "Nota: Los comandos de voz requieren una clave API Groq configurada.",
      'understood': "Entendido",
      'go_to_settings': "Ir a Configuración",
      'voice_commands_setup_msg': "Para usar comandos de voz, necesitas configurar una clave API Groq.",
      'options_label': "Opciones:",
      'get_key_at': "Obtén tu clave en: console.groq.com",
      'later': "Después",
      'configure': "Configurar",
      'whatsapp_error': "No se pudo abrir WhatsApp.",
      'attachments_label': "Adjuntos",
      'delete_installment_msg': "Esta es una transacción en cuotas. ¿Qué deseas hacer?",
      'delete_this': "Eliminar esta",
      'delete_all': "Eliminar todas",
      'cancelled_status': "Cancelado",
      'events_exported_success_suffix': " eventos exportados con éxito!",
      'no_events_to_export': "No hay eventos para exportar.",
      'mic_disabled': "Micrófono desactivado",
      'voice_commands_disabled_title': "ℹ️ Comandos de voz desactivados",
      'manual_usage_option': "✓ Usar la app manualmente (botones y formularios)",
      'enable_voice_option': "✓ Habilitar comandos de voz en:",
      'enable_voice_path': "  Menú → Configuración → Habilitar comandos de voz",
      'api_key_not_configured': "Clave API no configurada",
      'api_key_warning_title': "⚠️ Clave API no configurada",
      'configure_api_option': "1. Configura una clave API gratuita",
      'disable_voice_option': "2. Desactiva comandos de voz y usa la app manualmente",
      'period_label': "Período: ",
      'total_transactions': "Total Transacciones: ",
      'total_income': "Ingresos: ",
      'total_expense': "Gastos: ",
      'balance_label': "Saldo: ",
      'table_date': "Fecha",
      'table_description': "Descripción",
      'table_category': "Categoría",
      'table_value': "Valor",
      'category_breakdown': "Desglose por Categoría",
      
      // Messages
      'msg_enable_voice': "Habilite comandos de voz en Configuración para usar el micrófono",
      'msg_configure_api': "Configure una clave API en Configuración para usar comandos de voz",
      'about_title': "Acerca de FinAgeVoz",
      'about_version': "Versión 1.0.0",
      'about_description': "Su asistente financiero y de calendario inteligente.",
      'about_developed_by': "Desarrollado por:",
      'about_company': "Multiverso Digital",
      'about_email_label': "Correo electrónico:",
      'about_email': "contato@multiversodigita.com.br",
      
      // Help Dialog
      'help_title': "Comandos de Voz",
      'help_transactions': "💰 Transacciones:",
      'help_trans_1': "• \"Gasté 50 dólares en la panadería\"",
      'help_trans_2': "• \"Recibí 1000 dólares de salario\"",
      'help_trans_3': "• \"Compré TV de 2000 dólares en 10 cuotas\"",
      'help_agenda': "📅 Calendario:",
      'help_agenda_1': "• \"Reunión mañana a las 2pm\"",
      'help_agenda_2': "• \"Pagar luz el día 15\"",
      'help_attachments': "📎 Adjuntos y Compartir:",
      'help_attach_1': "• Agregue fotos y PDFs a transacciones y eventos.",
      'help_attach_2': "• Comparta informes vía WhatsApp.",
      'help_settings': "⚙️ Configuración:",
      'help_settings_1': "• Controle si la app habla los eventos al iniciar.",
      'help_settings_2': "• Administre categorías e idioma.",
      'help_navigation': "📱 Navegación:",
      'help_nav_1': "• \"Abrir finanzas\"",
      'help_nav_2': "• \"Abrir calendario\"",
      'help_nav_3': "• \"Ver informes\"",
      'help_tips': "💡 Consejos:",
      'help_tip_1': "• Hable naturalmente.",
      'help_tip_2': "• Espere a que el micrófono pulse.",
      'help_important': "⚠️ Importante:",
      'help_imp_1': "• El reconocimiento de voz requiere internet.",
      'help_imp_2': "• Si se alcanza el límite de datos del operador, los comandos pueden dejar de funcionar.",
      'help_api_limit': "🔑 Límite de API:",
      'help_api_1': "• La app usa inteligencia artificial con límite diario gratuito.",
      'help_api_2': "• Si alcanza el límite, espere unas horas o configure una nueva clave API.",
      'help_api_3': "• Vaya a Menú → Configuración → Groq API Key para agregar su propia clave.",
      'help_api_4': "• Obtenga una clave gratuita en: console.groq.com",
      'help_recommendation': "💎 Recomendación para Uso Intensivo:",
      'help_rec_1': "• Para hasta 100 transacciones/día, recomendamos el plan pago de Groq.",
      'help_rec_2': "• Modelo: Llama 3.3 70B Versatile",
      'help_rec_3': "• Costo: ~USD 10.35/mes (pago por uso)",
      'help_rec_4': "• Sin límite diario, alta precisión y velocidad.",
      'menu_exit': "Salir",
      
      // Finance
      'finance_title': "Finanzas",
      'balance_total': "Saldo Total",
      'income': "Ingresos",
      'expenses': "Gastos",
      'filter_all': "Todos",
      'filter_income': "Ingresos",
      'filter_expense': "Gastos",
      'add_transaction': "Añadir Transacción",
      'is_installment': "¿A plazos?",
      'down_payment': "Pago Inicial",
      'installment_count': "Nº de Cuotas",
      'installment_amount': "Importe de la Cuota",
      'total_calculated': "Total Calculado: ",
      'empty_transactions': "No se encontraron transacciones.",
      'select_date': "Seleccionar Fecha",
      'period_today': "Hoy",
      'period_week': "Esta Semana",
      'search_hint': "Buscar transacciones...",
      
      // Agenda
      'agenda_title': "Agenda",
      'empty_events': "No hay eventos para este día.",
      'search_hint_events': "Buscar eventos...",
      
      // Reports
      'reports_title': "Informes",
      'period_month': "Este Mes",
      'period_quarter': "Este Trimestre",
      'period_year': "Este Año",
      'chart_income_expense': "Ingresos vs Gastos",
      'chart_expenses_category': "Gastos por Categoría",
      'detailed_transactions': "Transacciones Detalladas",
      'export_pdf': "Exportar PDF",
      'installments_report_title': "Informe de Cuotas",
      'share_whatsapp': "Compartir en WhatsApp",
      'error_share_pdf': "Error al compartir PDF: ",
      'no_installments_found': "No se encontraron cuotas",
      'year_filter': "Año: ",
      'month_filter': "Mes: ",
      'no_filtered_installments': "No se encontraron cuotas con los filtros seleccionados",
      'total_label': "Total: ",
      'advanced_filters': "Filtros Avanzados",
      'view_installments': "Ver Cuotas",
      'share': "Compartir",
      'clear': "Limpiar",
      'period_quarter_short': "Trimestre",
      'period_year_short': "Año",
      'period_last_7': "Últimos 7 días",
      'period_last_30': "Últimos 30 días",
      'period_last_90': "Últimos 90 días",
      'categories_count': "categoría(s)",
      'subcategories_count': "subcategoría(s)",
      'filtered_values': "Valores filtrados",
      'no_expenses': "sin gastos",
      'no_income': "sin ingresos",
      'no_installments': "sin cuotas",
      'no_single_payments': "sin pagos únicos",
      
      // Categories
      'categories_title': "Categorías",
      'tab_expense': "Gastos",
      'tab_income': "Ingresos",
      'add_category': "Nueva Categoría",
      'edit_category': "Editar Categoría",
      'delete_category': "Eliminar Categoría",
      'confirm_delete': "¿Está seguro de que desea eliminar?",
      'cancel': "Cancelar",
      'save': "Guardar",
      'delete': "Eliminar",
      'name': "Nombre",
      'amount': "Importe",
      'date': "Fecha",
      'category': "Categoría",
      'subcategory': "Subcategoría",
      'type': "Tipo",
      'description': "Descripción",
      'close': "Cerrar",
      'delete_transaction': "Eliminar Transacción",
      'delete_event': "Eliminar Evento",
      'expense': "Gasto",
      'no_transactions': "No se encontraron transacciones",
      'no_events': "No se encontraron eventos",
      'transfer': "Transferir",
      'cancel_event': "Cancelar",
      'reactivate': "Reactivar",
      'reverse': "Revertir",
      'edit': "Editar",
      'confirm_reverse': "Confirmar reversión de",
      'reversal_of': "Reversión de",
      'is_expense': "¿Es gasto?",
      'invalid_data': "Datos inválidos",
      'pdf_generated': "¡PDF generado con éxito!",
      'error': "Error",
      'data_management': "Gestión de Datos",
      'database_statistics': "Estadísticas de la Base de Datos",
      'transactions': "transacciones",
      'events': "eventos",
      'categories': "categorias",
      'sign_in': "Iniciar Sesión",
      'sign_out': "Cerrar Sesión",
      'signed_in_as': "Conectado como",
      'backup_and_clean': "Copia de Seguridad y Limpieza",
      'clean_data_older_than': "Limpiar datos anteriores a",
      '6_months': "6 meses",
      '1_year': "1 año",
      '2_years': "2 años",
      'backup_and_clean_button': "Hacer Copia y Limpiar",
      'available_backups': "Copias Disponibles",
      'no_backups': "No se encontraron copias",
      'restore': "Restaurar",
      'confirm_backup_clean': "Confirmar Copia y Limpieza",
      'confirm_backup_clean_message': "Los datos antiguos se guardarán en Google Drive y luego se eliminarán del dispositivo. ¿Desea continuar?",
      'continue': "Continuar",
      'google_signin_failed': "Error al iniciar sesión en Google",
      'backup_success': "Copia de seguridad realizada con éxito",
      'confirm_restore': "Confirmar Restauración",
      'confirm_restore_message': "Se importarán los datos de la copia de seguridad. ¿Desea continuar?",
      'restore_success': "Datos restaurados con éxito",
      'database_size': "Tamaño de la Base de Datos",
      'of_max_size': "del tamaño máximo",
      'quick_access': "ACCESO RÁPIDO",

      'no_categories': "No se encontraron categorías",
      'no_subcategories': "Sin subcategorías",
      'status': "Estado",
      'cancelled': "Cancelado",
      'danger_zone': "Zona de Peligro",
      'wipe_all_data': "Borrar TODOS los Datos",
      
      // Settings / Onboarding
      'settings_title': "Configuración",
      'onboarding_title': "Configuración Inicial",
      'wake_word_label': "Contraseña de Voz",
      'wake_word_hint': "Ej: Jarvis",
      'language_label': "Idioma",
      'groq_label': "IA Groq (Opcional)",
      'groq_desc': "Para una respuesta mucho más rápida, use Groq.",
      'groq_hint': "gsk_...",
      'save_continue': "Guardar y Continuar",
      'save_btn': "Guardar",
      'error_password': "Por favor, establezca una contraseña de voz.",
      'saved_settings': "¡Configuración guardada!",
      'classify_transaction': "Clasificar Transacción",
      'policy_title': "Política de Privacidad",
      'about_title': "Acerca de",
      'version_label': "Versión",
      'developed_by': "Desarrollado por:",
      'contact_label': "Contacto:",
      'help_usage_title': "Cómo usar FinAgeVoz",
      'important_label': "Importante:",
      'command_examples_label': "Ejemplos de Comandos:",
      'understood_btn': "Entendido",
      'help_tooltip': "Ayuda",
      'categories_tooltip': "Categorías",
      'error_pdf_gen': "Error al generar PDF",
      'get_groq_key_title': "Obtener Clave Groq",
      'no_key_link': "¿No tiene una clave? Haga clic aquí",
      'how_to_get_key_tooltip': "¿Cómo obtener la clave?",
      'mic_init_error': "Error al iniciar micrófono. Intente de nuevo.",
      'category_name_label': "Nombre",
      'category_desc_label': "Descripción",
      'subcategory_name_label': "Nombre de Subcategoría",
      'add_subcategory_tooltip': "Añadir Subcategoría",
      'delete_category_error': "No se puede eliminar categoría con transacciones asociadas.",
      'groq_api_key_label': "Clave API Groq",
      'settings_general': "General",
      'settings_announce_events': "Siempre anunciar eventos",
      'settings_announce_events_desc': "Hablar eventos al abrir la app incluso si ya se dijeron",
      'settings_enable_voice': "Habilitar comandos de voz",
      'settings_enable_voice_desc': "Usar IA para procesar comandos de voz",
      'voice_enabled_msg': "Comandos de voz habilitados. Reinicie la app para aplicar.",
      'voice_disabled_msg': "Comandos de voz desabilitados. Use la app manualmente.",
      'settings_data': "Datos",
      'settings_reset_categories': "Restablecer Categorías",
      'settings_reset_categories_desc': "Restaura las categorías predeterminadas",
      'settings_reset_app': "Restablecer App (Borrar Todo)",
      'settings_reset_app_desc': "Borra todas las transacciones y eventos",
      'settings_api_title': "API para Comandos de Voz",
      'settings_api_in_use': "API en uso:",
      'settings_no_api': "Ninguna API configurada",
      'settings_configured': "Configurada",
      'settings_not_configured': "No configurada",
      'how_to_get_key_title': "Cómo obtener su clave API Groq:",
      'get_key_step_1': "1. Vaya a: console.groq.com",
      'get_key_step_2': "2. Inicie sesión o cree una cuenta gratuita",
      'get_key_step_3': "3. Vaya a \"API Keys\" en el menú lateral",
      'get_key_step_4': "4. Haga clic en \"Create API Key\"",
      'get_key_step_5': "5. Copie la clave generada (comienza con \"gsk_\")",
      'paste_key_below': "Pegue su clave a continuación:",
      'api_key_label': "Clave API",
      'api_key_helper': "Obligatorio para usar la app",
      'api_key_updated': "¡Clave API actualizada!",
      'confirm_reset_categories_title': "¿Restablecer Categorías?",
      'confirm_reset_categories_msg': "Esto restaurará las categorías originales. Las categorías personalizadas no se verán afectadas, pero los nombres predeterminados se restablecerán al idioma actual.",
      'reset': "Restablecer",
      'categories_reset_success': "¡Categorías restablecidas con éxito!",
      'confirm_wipe_title': "¿Borrar TODO?",
      'confirm_wipe_msg': "¿Está seguro de que desea eliminar TODAS las transacciones y eventos? Esta acción no se puede deshacer.",
      'wipe_all': "Borrar TODO",
      'data_wiped_msg': "Datos borrados: {transactions} transacciones, {events} eventos.",
      'error_prefix': "Error: ",
      'language_changed_msg': "Idioma cambiado. Reinicie la app para aplicar en todas las pantallas.",
      
      // Categories & Subcategories
      'cat_housing': "Vivienda",
      'cat_food': "Alimentación",
      'cat_transport': "Transporte",
      'cat_health': "Salud",
      'cat_education': "Educación",
      'cat_personal': "Gastos Personales",
      'cat_leisure': "Ocio",
      'cat_subscriptions': "Suscripciones y Servicios Digitales",
      'cat_financial': "Servicios Financieros",
      'cat_investments': "Inversiones",
      'cat_taxes': "Impuestos",
      'cat_pet': "Mascotas",
      'cat_fixed_assets': "Activos Fijos",
      'cat_other': "Otros Gastos",
      'inc_salary': "Salario",
      'inc_benefits': "Beneficios",
      'inc_other': "Otros Ingresos",
      'sub_rent': "Alquiler",
      'sub_condo': "Comunidad",
      'sub_water': "Agua",
      'sub_electricity': "Electricidad",
      'sub_gas': "Gas",
      'sub_landline': "Teléfono Fijo",
      'sub_internet': "Internet",
      'sub_home_insurance': "Seguro de Hogar",
      'sub_maintenance': "Mantenimiento y Reparaciones",
      'sub_domestic_services': "Servicios Domésticos",
      'sub_cleaning': "Artículos de Limpieza",
      'sub_supermarket': "Supermercado",
      'sub_produce': "Frutería/Verdulería",
      'sub_market': "Mercado",
      'sub_restaurants': "Restaurantes/Bares",
      'sub_cafes': "Cafeterías",
      'sub_delivery': "Entrega y Apps",
      'sub_vehicle_rent': "Financiación/Alquiler de Vehículo",
      'sub_fuel': "Combustible",
      'sub_public_transport': "Transporte Público",
      'sub_vehicle_maintenance': "Mantenimiento de Vehículo",
      'sub_vehicle_tax': "Impuesto Vehicular",
      'sub_vehicle_insurance': "Seguro de Auto",
      'sub_parking': "Estacionamiento",
      'sub_tolls': "Peajes",
      'sub_fines': "Multas",
      'sub_health_plan': "Seguro Médico",
      'sub_appointments': "Citas Médicas",
      'sub_exams': "Exámenes",
      'sub_medicines': "Medicamentos",
      'sub_pharmacy': "Farmacia",
      'sub_dentist': "Dentista",
      'sub_therapies': "Terapias",
      'sub_optics': "Óptica",
      'sub_medical_devices': "Dispositivos Médicos",
      'sub_school': "Escuela/Matrícula",
      'sub_college': "Universidad/Posgrado",
      'sub_courses': "Cursos Extracurriculares",
      'sub_supplies': "Material Escolar",
      'sub_books': "Libros",
      'sub_online_courses': "Cursos Online",
      'sub_clothing': "Ropa y Calzado",
      'sub_hygiene': "Higiene Personal",
      'sub_cosmetics': "Cosméticos y Maquillaje",
      'sub_salon': "Peluquería",
      'sub_barber': "Barbería",
      'sub_gym': "Gimnasio y Deportes",
      'sub_gifts': "Regalos",
      'sub_travel': "Viajes",
      'sub_hotels': "Hotéis",
      'sub_entertainment': "Cine/Teatro/Espectáculos",
      'sub_tickets': "Entradas y Eventos",
      'sub_hobbies': "Pasatiempos",
      'sub_clubs': "Clubes",
      'sub_games': "Juegos",
      'sub_tv': "TV por Suscripción",
      'sub_streaming': "Netflix y Streaming",
      'sub_software': "Suscripciones de Software",
      'sub_cloud': "Almacenamiento en la Nube",
      'sub_credit_card_fee': "Cuota de Tarjeta de Crédito",
      'sub_loans': "Préstamos",
      'sub_bank_fees': "Comisiones Bancarias",
      'sub_insurance': "Seguros",
      'sub_consortium': "Consorcios",
      'sub_income_tax': "Impuesto sobre la Renta",
      'sub_property_tax': "Impuesto sobre Bienes Inmuebles",
      'sub_govt_fees': "Tasas Gubernamentales",
      'sub_pet_food': "Comida para Mascotas",
      'sub_vet': "Veterinario",
      'sub_pet_grooming': "Peluquería Canina",
      'sub_pet_toys': "Juguetes y Accesorios",
      'sub_donations': "Donaciones",
      'sub_unexpected': "Imprevistos",
      'sub_monthly_salary': "Salario Mensual",
      'sub_advance': "Adelanto de Salario",
      'sub_13_salary': "Aguinaldo",
      'sub_vacation': "Vacaciones",
      'sub_bonus': "Bonos/Comisiones",
      'sub_meal_voucher': "Vale de Comida",
      'sub_transport_voucher': "Vale de Transporte",
      'sub_home_office': "Ayuda Home Office",
      'sub_dividends': "Dividendos",
      'sub_jcp': "Intereses sobre Capital",
      'sub_fixed_income': "Renta Fija",
      'sub_rent_received': "Alquileres Recibidos",
      'sub_sale_assets': "Venta de Activos",
      'sub_refunds': "Reembolsos",
      'sub_cash_gifts': "Regalos en Efectivo",
      'sub_appliances': "Electrodomésticos",
      'sub_computer': "Computadora",
      'sub_printer': "Impresora",
      'sub_mobile': "Teléfono Móvil",
      'sub_car': "Automóvil",
      'sub_furniture': "Muebles",
      'sub_machines': "Máquinas",
      'sub_equipment': "Equipo",
      'recurrence': "Recurrencia",
      'recurrence_none': "Ninguna",
      'recurrence_daily': "Diaria",
      'recurrence_weekly': "Semanal",
      'recurrence_monthly': "Mensual",
      'recurrence_yearly': "Anual",
      'add_event': "Añadir Evento",
      'edit_event': "Editar Evento",
      'title': "Título",
      'required_field': "Campo obligatorio",
    },
  };

  static String t(String key, String lang) {
    if (_localizedValues.containsKey(lang) && _localizedValues[lang]!.containsKey(key)) {
      return _localizedValues[lang]![key]!;
    }
    // Fallback to English
    if (_localizedValues.containsKey('en') && _localizedValues['en']!.containsKey(key)) {
      return _localizedValues['en']![key]!;
    }
    return key;
  }

  static String tCategory(String name, String lang) {
    // Helper to remove accents for matching
    String normalize(String input) {
      const accentMap = {
        'á':'a','ã':'a','â':'a','à':'a',
        'é':'e','ê':'e',
        'í':'i',
        'ó':'o','ô':'o','õ':'o',
        'ú':'u',
        'ç':'c',
        'Á':'A','Ã':'A','Â':'A','À':'A',
        'É':'E','Ê':'E',
        'Í':'I',
        'Ó':'O','Ô':'O','Õ':'O',
        'Ú':'U',
        'Ç':'C',
      };
      var result = input;
      accentMap.forEach((k, v) => result = result.replaceAll(k, v));
      return result;
    }

    final trimmed = name.trim();
    final normalized = normalize(trimmed).toLowerCase();

    // Direct lookup
    final key = _categoryKeyMap[trimmed];
    if (key != null) {
      return t(key, lang);
    }

    // Case‑insensitive & accent‑insensitive match
    for (final entry in _categoryKeyMap.entries) {
      if (normalize(entry.key).toLowerCase() == normalized) {
        return t(entry.value, lang);
      }
    }

    // Partial match fallback
    for (final entry in _categoryKeyMap.entries) {
      final entryNorm = normalize(entry.key).toLowerCase();
      if (entryNorm.contains(normalized) || normalized.contains(entryNorm)) {
        return t(entry.value, lang);
      }
    }

    return name;
  }

  static final Map<String, String> _categoryKeyMap = {
    // Expenses
    'Habitação': 'cat_housing',
    'Alimentação': 'cat_food',
    'Transporte': 'cat_transport',
    'Saúde': 'cat_health',
    'Educação': 'cat_education',
    'Despesas Pessoais': 'cat_personal',
    'Lazer': 'cat_leisure',
    'Assinaturas e Serviços Digitais': 'cat_subscriptions',
    'Serviços Financeiros': 'cat_financial',
    'Investimentos': 'cat_investments',
    'Impostos e Tributos': 'cat_taxes',
    'Pet': 'cat_pet',
    'Imobilizado': 'cat_fixed_assets',
    'Outras Despesas': 'cat_other',
    
    // Income
    'Salário': 'inc_salary',
    'Benefícios': 'inc_benefits',
    'Outras Receitas': 'inc_other',
    
    // Subcategories - Housing
    'Aluguel Residência': 'sub_rent',
    'Condomínio': 'sub_condo',
    'Água': 'sub_water',
    'Luz (Eletricidade)': 'sub_electricity',
    'Gás': 'sub_gas',
    'Telefone Fixo': 'sub_landline',
    'Internet Residencial': 'sub_internet',
    'Seguro Residencial': 'sub_home_insurance',
    'Manutenção e Reparos': 'sub_maintenance',
    'Serviços Domésticos': 'sub_domestic_services',
    'Materiais de Limpeza': 'sub_cleaning',
    
    // Food
    'Supermercado': 'sub_supermarket',
    'Sacolão/Hortifrúti': 'sub_produce',
    'Feira': 'sub_market',
    'Restaurantes/Bares': 'sub_restaurants',
    'Lanchonetes/Cafeterias': 'sub_cafes',
    'Delivery e Aplicativos': 'sub_delivery',
    
    // Transport
    'Financiamento/Aluguel de Veículo': 'sub_vehicle_rent',
    'Combustível': 'sub_fuel',
    'Ônibus/Metrô/Aplicativos': 'sub_public_transport',
    'Manutenção do Veículo': 'sub_vehicle_maintenance',
    'IPVA/Licenciamento': 'sub_vehicle_tax',
    'Seguro Auto': 'sub_vehicle_insurance',
    'Estacionamento e Garagem': 'sub_parking',
    'Pedágios': 'sub_tolls',
    'Multas': 'sub_fines',
    
    // Health
    'Plano de Saúde': 'sub_health_plan',
    'Consultas Médicas': 'sub_appointments',
    'Exames': 'sub_exams',
    'Medicamentos': 'sub_medicines',
    'Despesas com Farmácia/Drogaria': 'sub_pharmacy',
    'Dentista/Odontologia': 'sub_dentist',
    'Fisioterapia e Terapias': 'sub_therapies',
    'Ótica/Lentes/Óculos': 'sub_optics',
    'Aparelhos Auditivos/Ortopédicos': 'sub_medical_devices',
    
    // Education
    'Escola/Mensalidades': 'sub_school',
    'Faculdade/Pós-graduação': 'sub_college',
    'Cursos Extracurriculares': 'sub_courses',
    'Material Escolar/Acessórios': 'sub_supplies',
    'Livros e Publicações': 'sub_books',
    'Cursos Online e Plataformas': 'sub_online_courses',
    
    // Personal
    'Vestuário e Calçados': 'sub_clothing',
    'Higiene Pessoal': 'sub_hygiene',
    'Cosméticos e Maquiagem': 'sub_cosmetics',
    'Salão de Beleza/Cabeleireiro': 'sub_salon',
    'Barbeiro': 'sub_barber',
    'Academia e Atividades Esportivas': 'sub_gym',
    'Presentes': 'sub_gifts',
    
    // Leisure
    'Viagens': 'sub_travel',
    'Hotéis e Pousadas': 'sub_hotels',
    'Cinema/Teatro/Shows': 'sub_entertainment',
    'Ingressos e Eventos': 'sub_tickets',
    'Hobbies e Coleções': 'sub_hobbies',
    'Mensalidades de Clubes/Associações': 'sub_clubs',
    'Jogos e Assinaturas de Games': 'sub_games',
    
    // Subscriptions
    'Plano de TV por Assinatura': 'sub_tv',
    'Netflix e Outras Plataformas': 'sub_streaming',
    'Assinaturas de Software': 'sub_software',
    'Armazenamento em Nuvem': 'sub_cloud',
    
    // Financial
    'Cartão de Crédito (Anuidade)': 'sub_credit_card_fee',
    'Empréstimos e Financiamentos': 'sub_loans',
    'Tarifas Bancárias': 'sub_bank_fees',
    'Seguros Diversos': 'sub_insurance',
    'Consórcios': 'sub_consortium',
    
    // Taxes
    'Imposto de Renda': 'sub_income_tax',
    'IPTU': 'sub_property_tax',
    'Taxas Governamentais': 'sub_govt_fees',
    
    // Pet
    'Ração e Alimentação': 'sub_pet_food',
    'Veterinário/Vacinas': 'sub_vet',
    'Banho e Tosa': 'sub_pet_grooming',
    'Acessórios e Brinquedos': 'sub_pet_toys',
    
    // Fixed Assets
    'Eletrodomésticos': 'sub_appliances',
    'Computador': 'sub_computer',
    'Impressora': 'sub_printer',
    'Celular': 'sub_mobile',
    'Automóvel': 'sub_car',
    'Móveis e utensilios': 'sub_furniture',
    'Máquinas': 'sub_machines',
    'Equipamento': 'sub_equipment',

    // Other
    'Doações/Caridade': 'sub_donations',
    'Imprevistos': 'sub_unexpected',
    
    // Income Subs
    'Salário Mensal': 'sub_monthly_salary',
    'Adiantamento': 'sub_advance',
    '13º Salário': 'sub_13_salary',
    'Férias': 'sub_vacation',
    'Bônus/Comissões': 'sub_bonus',
    'Vale Alimentação/Refeição': 'sub_meal_voucher',
    'Vale Transporte': 'sub_transport_voucher',
    'Auxílio Home Office': 'sub_home_office',
    'Dividendos': 'sub_dividends',
    'Juros sobre Capital Próprio': 'sub_jcp',
    'Renda Fixa (CDB, Tesouro)': 'sub_fixed_income',
    'Aluguéis Recebidos': 'sub_rent_received',
    'Venda de Bens': 'sub_sale_assets',
    'Reembolsos': 'sub_refunds',
    'Presentes em Dinheiro': 'sub_cash_gifts',
  };
}
